### ISSUE TITLE
Fix the Assignable Scopes on the "StartVMonConnect-AVD" Role Definition

### ISSUE THREAD

**Issue by jamasten** [Azure/avdaccelerator#102]
### Problem
The AVD Accelerator solution creates the "StartVMonConnect-AVD" role definition for the Start VM On Connect feature.  This role definition is deployed with a single assignable scope for one subscription.  When deploying the solution to another subscription within the same tenant, the deployment fails since the role already exists at a different assignable scope and updates are not permitted.

### Background Info
Though assignable scopes can be set to Management Groups, that feature is in preview and cannot be set to tenant root management group.  Only built-in roles are allowed at the root.  

**References:**

- [Custom Role Limits](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles#custom-role-limits)
- [Assignable Scopes](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-definitions#assignablescopes)

### Suggestions

Here are some ideas to solve the issue:

- Use a deployment script to check if the role definition already exists.  If it does, update the assignable scopes with the new subscription's resource ID using the [Set-AzRoleDefinition](https://docs.microsoft.com/en-us/powershell/module/az.resources/Set-azRoleDefinition?view=azps-7.5.0) cmdlet.  If it doesn't, deploy the role definition.  The role definition resource should have a condition that checks the output from the deployment script to determine whether the role definition should be deployed or not.
- Create a role definition for each assignable scope to avoid conflicts: roleName: 'StartVmOnConnect_${subscription().subscriptionId}'

**Comment by danycontre** [comment]
@jamasten is this still valid? we pushed changes to permissions assignments for the baseline deployment.

**Comment by jamasten** [comment]
There is a built-in role for Start VM on Connect now, "Desktop Virtualization Power On Contributor", which resolves any of the issues I described here.  As long as this has been implemented in the baseline, then this issue can be closed.

Reference: https://learn.microsoft.com/en-us/azure/virtual-desktop/start-virtual-machine-connect?tabs=azure-portal#assign-the-desktop-virtualization-power-on-contributor-role-with-the-azure-portal

**Comment by danycontre** [comment]
Code was updated to use "Desktop Virtualization Power On Contributor" built-in role.
