### ISSUE TITLE
Alignment for all Azure Resources Deployed to CAF Naming Standards

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#107]
Work in conjunction with the ALZ bicep on naming standard for deployed resources

ALZ bicep linked item:
https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113637

**Comment by danycontre** [comment]
We are consistently asked by customers, partners and the field as to why ALZ/ESLZ doesn't algin to the CAF Naming Standards as defined in the links below:

- [Develop your naming and tagging strategy for Azure resources - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
- [Define your naming convention - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
- [Recommended abbreviations for Azure resource types - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)

We should assess and align our default values for resource naming parameters, where appropriate and agreed upon (also with the ALZ Terraform Module team ([@Kevin Rowlandson](https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113637#), [@Matt White](https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113637#), [@Jack Tracey](https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113637#)) to set the values to align to the CAF naming standards. ALZ TF also has this on their roadmap to address also tracked here: [Feature Request - user specified naming convention · Issue #292 · Azure/terraform-azurerm-caf-enterprise-scale (github.com)](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/292).

We should also collaborate with [@Dany Contreras](https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113637#) as they are doing the same for the AVD Accelerator, so we should try and be consistent, where possible!

Straight off the bat there are some resources we all disagree with like prefixing all Management Groups with `mg-` and DNS zones with `dnsz-` as it doesn't make sense or technically work.

**Comment by danycontre** [comment]
Dost created the following onenote to track naming discussions: https://microsoft-my.sharepoint.com/personal/dostmuh_microsoft_com/_layouts/15/Doc.aspx?sourcedoc={fc32cb55-fe05-4680-9b30-b9a015d710a4}&action=edit&wd=target%28AVD%20naming%20convention.one%7Ca6fd29e2-29c0-4553-9427-86731f3cfc79%2FAvd%20accelerator%7C082d432f-bacd-489f-884f-c668500408a4%2F%29&wdorigin=NavigationUrl

**Comment by Dost2010** [comment]
We Agreed on the naming convention and final name is in onenote. 
Next Task: Implement naming convention in code.

**Comment by danycontre** [comment]
Thanks for your contribution @Dost2010 
Updates submitted on PR: https://github.com/Azure/avdaccelerator/pull/132

**Comment by poirierpierluc** [comment]
Is there any update on this? We're still forced to use the root_id prefix.
