### ISSUE TITLE
Alignment for all Azure Resources Deployed to CAF Tagging Standards

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#108]
Work in conjunction with the ALZ bicep on tagging standard for deployed resources

ALZ bicep linked item:
https://unifiedactiontracker.visualstudio.com/Solution%20Engineering/_workitems/edit/113638

**Comment by danycontre** [comment]
Description from ALZ bicep item:

We are consistently asked by customers, partners and the field as to why ALZ/ESLZ doesn't algin to the CAF Tagging Standards as defined in the links below:

- [Develop your naming and tagging strategy for Azure resources - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
- [Define your tagging strategy - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-tagging)

We should assess and align our default values for tagging parameters, where appropriate and agreed upon (also with the ALZ Terraform Module team ([@Kevin Rowlandson](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_backlogs/backlog/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback/?showParents=true&workitem=113637#), [@Matt White](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_backlogs/backlog/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback/?showParents=true&workitem=113637#), [@Jack Tracey](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_backlogs/backlog/Azure%20Landing%20Zone%20Bicep/Backlog%20Bugs%20Feedback/?showParents=true&workitem=113637#)) to set the values to align to the CAF tagging standards.

We should also collaborate with [@Dany Contreras](https://dev.azure.com/unifiedactiontracker/Solution%20Engineering/_sprints/backlog/Azure%20Landing%20Zone%20Bicep/Solution%20Engineering/Copper/202206?workitem=113637#) as they are doing the same for the AVD Accelerator, so we should try and be consistent, where possible!

Acceptance criteria:

1. Assess what, if any, tags we will assign to the tag supporting resources in ALZ and what values we will set
2. Agree with ALZ team on SCRUM calls
3. Implement in ALZ Bicep

**Comment by anlucen** [comment]
It was worked on the tagging names, string and key for several resources and component based on CAF best practices and AVD ESL architecture. It was also shared with the AVD Scrum team for open feedback. 
**Next step:** work in the Bicep code

**Comment by anlucen** [comment]
Last final update: The code Bicep was built, and thanks to @danycontre  help were possible to merge this in the main branch for testing and future feedback. The Portal UI was constructed as well. Closing this issue
