### ISSUE TITLE
Create Azure Files for FSLogix Profile Containers

### ISSUE THREAD

**Issue by edm-ms** [Azure/avdaccelerator#11]
As part of the main landing zone deployment we should prompt for creation of a storage account to support profile containers. 

We should also prompt to integrate Azure Backup for the files if the option above is selected. 

Private Link + Private DNS needs to be integrated as well.

- New/Existing Private DNS Zone
- New/Existing VNet to link zone

**Comment by danycontre** [comment]
We also need to get the DNS records on custom DNS or private zones.
