### ISSUE TITLE
Add Azure AAD DS as an identity source option

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#115]
- Join storage account to AAD DS
- Join session hosts to AAD DS

**Comment by TheAlistairRoss** [comment]
This is something I require for a MSFT customer with urgency.

**Comment by danycontre** [comment]
@TheAlistairRoss e are actively working on the code, what is the identity source your customer use, ADDS or AADDS ?

**Comment by danycontre** [comment]
cc: @nataliakon

**Comment by TheAlistairRoss** [comment]
Only ADDS.

**Comment by danycontre** [comment]
Code to add AADDS as an identity provider was built, tested and merged to main.

AAD option is currently being worked on issue #167
