### ISSUE TITLE
Integrate AVD accelerator with new AVD multi-region docs

### ISSUE THREAD

**Issue by xelizondo** [Azure/avdaccelerator#118]
link from AVD accelerator to BCDR to get more details
[Multiregion BCDR for Azure Virtual Desktop - Azure Architecture Center | Microsoft Docs](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-multi-region-bcdr)

**Comment by danycontre** [comment]
Migrated to ADO
