### ISSUE TITLE
AVD Monitoring

### ISSUE THREAD

**Issue by edm-ms** [Azure/avdaccelerator#13]
We need to deploy the monitoring workbook: https://docs.microsoft.com/en-us/azure/virtual-desktop/azure-monitor as part of the base deployment. 

We can create diagnostic settings in our build, and keep the name: setByPolicy to match ESLZ. 

We can prompt to create a new workspace, use an existing, or have it set by policy.

Re: the monitoring workbook we should see if we can get access to the template so that we can deploy it.

**Comment by florian-ried** [comment]
Hi Eric,
has this already been implemented because the topic was closed?
I'm currently asking myself the exact same question :)
Thank you for your response.
