### ISSUE TITLE
README.md flow

### ISSUE THREAD

**Issue by rallegroms** [Azure/avdaccelerator#131]
Suggested flow for the README.md document:

1. Overview
2. This repository
3. Baseline Architectural Diagram
4. 'Next Steps' rename to 'Getting Started' with a link to wiki
5. AVD Accelerator Baseline (with deploy to Azure link)
6. Optional: Custom Image Build (with deploy to Azure link)
7. Contributing/Trademarks

**Comment by danycontre** [comment]
cc: @nataliakon @xelizondo @wahidsaleemi

**Comment by xelizondo** [comment]
Setting a time to go over this later this week. Thanks @rallegroms !

**Comment by xelizondo** [comment]
Reorged section per feedback with minor adjustment on diagram section moved lower down to make the deployment option more visible

**Comment by rallegroms** [comment]
Thank you @xelizondo and @nataliakon...looks great!
