### ISSUE TITLE
Azure AD Scenario 

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#136]
Support for Azure AD Join VMs would be great.
Mainly for personal host pools scenarios for now.
Pooled scenarios with FSLogix Preview Feature would be awesome too. But I think there are many steps to automate.

**Comment by danycontre** [comment]
@florian-ried thanks for your feedback, we are currently working on adding new identity sources

**Comment by danycontre** [comment]
Functionality added to ARM/Bicep/Portal UI
