### ISSUE TITLE
Terraform code

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#142]
@jensheerin
Thank you so much for terraform code!
I have already tried to test this. However, I get the following error when creating the storage account. 
![image](https://user-images.githubusercontent.com/95634472/182147031-6edc16df-07a6-4128-96c1-a9f06da62fd4.png)

**Comment by florian-ried** [comment]
The following error has already been noted in the Terraform Plan. It was only when I commented out line 33 that I was able to successfully create a terraform plan.
![image](https://user-images.githubusercontent.com/95634472/182149216-4a0f6333-38c7-4a81-826e-6572f964f825.png)

**Comment by jensheerin** [comment]
Thank you @florian-ried for testing and logging issue! It has been corrected.
