### ISSUE TITLE
Configure Monitoring for AVD

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#147]
So far I have not seen any code example (Bicep, Terraform) configurations to correctly roll out Azure Monitor Insights for AVD. I think this is very important as a future feature.

**Comment by danycontre** [comment]
Great feedback, we are working on it

**Comment by danycontre** [comment]
Related to https://github.com/Azure/avdaccelerator/issues/155

**Comment by jensheerin** [comment]
Terraform updated to include monitoring.

**Comment by danycontre** [comment]
Testing Bicep/ARM/Portal UI code

**Comment by danycontre** [comment]
Work completed for ARM/Portal UI/Bicep/Terraform
