### ISSUE TITLE
Understanding AVD enterprise application ObjectID

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#154]
In order to understand the deployment better, I would be interested in what exactly this object ID is needed for. Thanks in advance for an explanation. 
Btw....  It's fun to work in this repository ;-)

Best
Florian

**Comment by danycontre** [comment]
Hey Florian, the enterprise app Azure Virtual Desktop (ApplicationID: 9cdead84-a844-4324-93f2-b2e6bb768d07) is used/needed when:
- Enabling Start VM on connect feature as roles will be granted to this identity during deployment.
- AVD scaling plan (in our backlog, not in the code today as it is not GA yet), this feature will also use the same identity when enabled.

Does it make sense? Please let us know if you have additional comments.

**Comment by florian-ried** [comment]
Thank you Dany!
Looking forward to Scaling Plan GA :)
