### ISSUE TITLE
Log Analytics Workspace

### ISSUE THREAD

**Issue by lenvolk** [Azure/avdaccelerator#155]
Please add LAW to monitor AVD, will help a lot for any t-shooting reasons

**Comment by danycontre** [comment]
Agree, we need this feature, it should allow to:

- Create new LAW or connect to existing one
- Deploy policy at sub level to apply monitoring settings
- Configure all AVD insights workbook settings

**Comment by xelizondo** [comment]
These 3 are around the same lines: #70 #147 , #155.

**Comment by danycontre** [comment]
Code in testing face to fully configure resources with AVD insights settings.

**Comment by danycontre** [comment]
Work completed for ARM/Portal UI/Bicep/Terraform
