### ISSUE TITLE
Permission to rollout in each scenario

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#157]
I have another suggestion for improvement. Maybe this already exists and I haven't found it yet.
It would be important to know what permissions are needed for each rollout. Contributor Rights sufficient on Azure? Global Administrator required or other API Permissions?

Best 
Florian

**Comment by danycontre** [comment]
Hey @florian-ried 

Permissions required are highlighted in the getting started guide: https://github.com/Azure/avdaccelerator/blob/main/workload/docs/getting-started.md

Please let us know if there is additional information required.

**Comment by florian-ried** [comment]
@danycontre 
Thanks for the quick response, that's great!
Regarding Terraform, I saw that the code also creates groups in Azure AD. Authorizations within Azure AD are therefore certainly necessary. It would be great if there was a hint as to which permissions are required exactly.
