### ISSUE TITLE
LZ portal-driven deployment is touchy about some fields

### ISSUE THREAD

**Issue by hooverken** [Azure/avdaccelerator#164]
I was working with the current version of the accelerator in the portal today (10 Aug 2022) and had a few minor items that caused failed deployments.  I did get it working but had to work around some things.  These are probably pretty easy to fix and/or avoid with some helpful wording...

1) The four-character "deployment prefix" apparently has to be all lowercase since it's concatenated with other stuff to create the storage account name.  If you use "ABCD" then the storage account creation fails but if you use "abcd" it's fine.  This requirement should be added to the tooltip for this field and the field should enforce it (or just force what the user enters through String.tolower() )

2) The admin password validation seems mildly broken.  It requires that the password meet three out of four criteria (upper, lower, digit, special) but if I enter a password that doesn't have any digits but otherwise meets the criteria the field validation still rejects it and the error is misleading because it actually wants a digit and not a special.  In the below screen shot I entered HappyBirthday! but it's being rejected when it should be OK based on the criteria.  If I add a digit it validates fine.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/70644066/184016283-007c6fda-9acb-4ee2-a096-ccee83a3acb8.png">

3) The format requirement for the "Storage account OU name" should be clarified.  Does this field want a full DN path to the OU or does it just want the name of an OU somewhere in the AD?  It also doesn't like whitespace --  "My Storage Account OU" creates a deployment failure.  I finally gave up and left it blank after I tried several things with no luck.  My suggested change for this is that the OU should be provided as a complete DN path just like for the session hosts, with the default being the same DN as for the session hosts if it's left blank.

This is a great accelerator, I look forward to using it with customers!

**Comment by danycontre** [comment]
@hooverken thanks for testing the code and submitting the issue.

Some comments:
1. This was a bug in the deployment template storage account naming variable was using deploymentPrefix in the calculation instead of deploymentPrefixLowercase (which is defined as toLower(deploymentPrefix))

**Comment by hooverken** [comment]
After doing a pull, item #1 in my list is definitely fixed.  Thanks!

For #2, I see the updated helper text and the regex but validation still doesn't like my "HappyBirthday!" example.  As before, if I enter a string that meets all four criteria (upper, lower, digit, special) it validates.  The regex probably needs further refinement.

**Comment by danycontre** [comment]
Thanks @hooverken for checking.

2. Work in progress
3. Code was updated to ask for storage OU path instead of storage OU name:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/78437433/185930995-d8a060df-8a14-4527-8491-62af68d49b13.png">

**Comment by danycontre** [comment]
cc: @moisesjgomez

**Comment by swathibhat1** [comment]
This feature/enhancement is completed
