### ISSUE TITLE
Terraform Module: Fileshare and KeyVault Private Endpoint Not Registered with Associated Private DNS Zone

### ISSUE THREAD

**Issue by spotakash** [Azure/avdaccelerator#168]
During test, I noticed Azure Fileshare service gets created with Private Endpoint and related Private DNS also (with Virtual Network Link). But, Fileshare Private Endpoint was not registered with Private DNS Zone. Same is the case for KeyVault. 

Here are screen shot in my current run.
![image](https://user-images.githubusercontent.com/7689697/185035264-c5ad28e3-7e31-42e1-b60c-6608da2e3123.png)

![image](https://user-images.githubusercontent.com/7689697/185035447-30422168-2b7b-49e7-aca9-7d7765098e8b.png)

**Comment by jensheerin** [comment]
@spotakash Thank you for the feedback! It is on the backlog for next update.

**Comment by jensheerin** [comment]
@spotakash Thank you again for logging issue. Code updated.

**Comment by florian-ried** [comment]
@jensheerin 
I just noticed that in my Terraform Deployment (Modules) the private endpoint was still not registered with the private DNS zone. Should the customization already be in the current code Terraform?

Thanks :) 
![image](https://user-images.githubusercontent.com/95634472/192797016-8b26ccb1-826b-433f-a2af-69bc4ba70bb7.png)
