### ISSUE TITLE
Suggestion: KeyVault Storage Account Name should not be randomized in tf file

### ISSUE THREAD

**Issue by spotakash** [Azure/avdaccelerator#169]
On Terraform Module: I see potential risk of environment breakage if we can make changes in variable. I observed in subsequent run, Random was triggering new keyvault or File share (storage account) creation, despite having state file

**Comment by jensheerin** [comment]
Thank you for the feedback. Added to the backlog.

**Comment by jensheerin** [comment]
Code updated.
