### ISSUE TITLE
Terraform - deploy multi subscription

### ISSUE THREAD

**Issue by mofaizal** [Azure/avdaccelerator#196]
Terraform 
-	The scenario I was trying the Image gallery and AD on Azure VM (VNET) configure at AVD LAB 1 Subscription. 
-	AVD Workspace and Hostpool deployed on AVD LAB 2 Subscription
-	Unable to deploy multiple subscriptions. The Image gallery and AD VNET must exist in same subscription.
-	We need to fix this otherwise we will have quota issue during LevelUp lab. 
-	RG name and Resource name need to include user prefix
![image](https://user-images.githubusercontent.com/35946439/189198048-04fd95ef-0bfc-4271-b0e5-2e6a465cee48.png)

**Comment by prasad3017** [comment]
@jensheerin Tagging you here
