### ISSUE TITLE
Portal – Single subscription  -  AVD Scaling plan = YES (default)  - FAIL  

### ISSUE THREAD

**Issue by mofaizal** [Azure/avdaccelerator#197]
Portal – Single subscription with Connect to AD and (Management Tab) AVD Scaling plan = YES (default)  - FAIL  
{
    "status": "Failed",
    "error": {
        "code": "PrincipalNotFound",
        "message": "Principal 9cdead84a844432493f2b2e6bb768d07 does not exist in the directory 449fbe1d-9c99-4509-9014-4fd5cf25b014. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
    }
}

![image](https://user-images.githubusercontent.com/35946439/189207744-db28c5e0-bad9-4265-88b9-3b89f63722a7.png)

 
![image](https://user-images.githubusercontent.com/35946439/189207769-2175c068-a118-4902-9e4b-db61e8c07eaa.png)

 
![image](https://user-images.githubusercontent.com/35946439/189207790-3a4bee0c-8b67-4584-87b2-b6758563d8ec.png)

**Comment by danycontre** [comment]
Hi @mofaizal error points to a wrong object ID provided at deployment time, please make sure the object ID is the one paired with application ID 9cdead84-a844-4324-93f2-b2e6bb768d07.

The enterprise application name can be "Windows Virtual Desktop" or "Azure Virtual Desktop" depending on when it was registered on your Azure AD tenant.

Example:
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/78437433/189682826-832d7096-a9b2-4ff5-b6b7-127b86122635.png">

**Comment by mofaizal** [comment]
Noted @danycontre on Object ID. No action required. Deployment is PASS. 

How to get object your application object ID 
- Go to Azure AD
- Click Enterprise Applications
- Remove Filter - Application ID start with
- Search "desktop"
- Find Windows Virtual Desktop and Copy Object ID.
