### ISSUE TITLE
Bicep/ARM/Portal UI - Private DNS zone creation

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#200]
Add logic to not only allow for the use of existing private DNS zones but also for the creation of new ones for:

- privatelink.file.core.windows.net
- privatelink.vaultcore.azure.net

Steps:

- Define placing for new resources (Subscription, RG)
- Use existing or create new
- If new deploy resources and link them to new vNet
- Update portal UI accordingly

**Comment by swathibhat1** [comment]
Feature/Enhancement moved to ADO board for tracking.
