### ISSUE TITLE
 imageReference in avd-session-hosts.bicep don't pass Azure/PSRule.Rules.Azure gives error

### ISSUE THREAD

**Issue by aavdberg** [Azure/avdaccelerator#204]
https://github.com/Azure/PSRule.Rules.Azure/issues/1656

**Comment by aavdberg** [comment]
Did try several things like.

```
imageReference: useSharedImage ? json(concat('{"id": "', avdImageTemplataDefinitionId, '"}')) : marketPlaceGalleryWindows 
```

but then I get the following warning from linter in vscode: 
```
Use string interpolation instead of the concat function.
```

**Comment by oxbo-andre** [comment]
This is solved by a https://github.com/Azure/PSRule.Rules.Azure/issues/1656

And release v1.20.0
