### ISSUE TITLE
Management Plane requesting the "AVD enterprise application ObjectID" - should be the "Application ID"

### ISSUE THREAD

**Issue by ubergeek24** [Azure/avdaccelerator#216]
On the Management Plane page there is a mandatory field that is asking for the "AVD enterprise application ObjectID". 

New users will try to figure out where this value comes from and potentially how to create this if they are unable to find it. I was able to find it here:
1. Azure Active Directory->Enterprise Applications
2. Clear the filters
3. Type "Azure Virtual Desktop" in the search filter
4. Locate the one that is listed as "Azure Virtual Desktop" - only (Note: There are 3 entries)
5. Select it and then copy the "Application ID" value

Also, hovering over the "info" bubble it also states:

Provide the ObjectID of the enterprise application Azure Virtual Desktop (ApplicationID: 9cdead84-a844-4324-93f2-b2e6bb768d07).

**Comment by danycontre** [comment]
@ubergeek24 thanks for the feedback, we realized the ask wasn't clear and recently updated the tooltip (bubble) info of the field to: 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/78437433/195934181-5434a776-b453-43f3-9536-966ecdcce083.png">
Please let us know if above makes it clearer or if additional info may be needed, any feedback ideas are welcome.
