### ISSUE TITLE
Incorporate PG recommended settings (Defender, Edge, check FSLogix exclusions)

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#230]
Incorporate PG recommended settings:

[Microsoft Defender Antivirus Virtual Desktop Infrastructure deployment guide | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fsecurity%2Fdefender-endpoint%2Fdeployment-vdi-microsoft-defender-antivirus%3Fview%3Do365-worldwide&data=05%7C01%7Cdany.contreras%40microsoft.com%7Ccb3873c1d32a48600cc708dab2822169%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638018569243294240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DYQ9%2BvIMtyEcV21fCEFgN0z8IZS%2FifSZ7DbJVoalOzY%3D&reserved=0)

[Microsoft Edge for Virtual desktop infrastructure (VDI) | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdeployedge%2Fedge-for-virtualized-desktop-infrastructure&data=05%7C01%7Cdany.contreras%40microsoft.com%7Ccb3873c1d32a48600cc708dab2822169%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638018569243294240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3gAmElKg0Cj4KD5mrXMbPuXtr57%2BLV2lcf9toYDw7Q0%3D&reserved=0)

[https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#storage-exclusions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fexample-scenario%2Fwvd%2Fwindows-virtual-desktop-fslogix%23storage-exclusions&data=05%7C01%7Cdany.contreras%40microsoft.com%7Ccb3873c1d32a48600cc708dab2822169%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638018569243294240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6RgFfhoAbSDhOetUOnIvZW%2FlKY5jnIHTQrPmucMPZmE%3D&reserved=0)

@nataliakon @jensheerin @swathibhat1

**Comment by swathibhat1** [comment]
Feature/ Enhancement for Incorporating PG recommended settings completed for Defender, FSLogix exclusions. Edge is tracked on the ADO
