### ISSUE TITLE
Docs section: Resource Organization- Resource Group Design

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#24]
Page section: Design Recommendations

Fix:
- Convert text code snippet for Resource Groups to a diagram or a bullet point list, to make it easier for users to consume.

**Comment by danycontre** [comment]
Agree, have the same comments from Cognizant during engagement, diagram will be easier to understand.

Also, we need to follow diagram design guidelines from other accelerator teams like AVS, since marketing team has already vetted their docs.

![image](https://user-images.githubusercontent.com/78437433/150203831-0296fed7-3ff1-4829-a507-21945b049872.png)

**Comment by xelizondo** [comment]
PR #3125 submitted

**Comment by danycontre** [comment]
PR #3125 submitted
