### ISSUE TITLE
'hostPoolRestrationInfo' is not valid

### ISSUE THREAD

**Issue by rickvdboor** [Azure/avdaccelerator#243]
Hey!

I just ran into an issue where the following error pops up:

The template output 'hostPoolRestrationInfo' is not valid: Template output JToken type is not valid. Expected 'Object'. Actual 'Null'

I've recently updated the avdaccelerator modules, but i'm not sure if that actually caused the issue. Anyone had this same problem?

avd-management-plane.bicep:
```
`// Hostpool.
module avdHostPool '../../../carml/1.2.0/Microsoft.DesktopVirtualization/hostpools/deploy.bicep' = {
  scope: resourceGroup('${avdWorkloadSubsId}', '${avdServiceObjectsRgName}')
  name: 'AVD-HostPool-${time}'
  params: {
    name: avdHostPoolName
    location: avdManagementPlaneLocation
    hostpoolType: avdHostPoolType
    startVMOnConnect: avdStartVmOnConnect
    customRdpProperty: varAvdHostPoolRdpPropertiesDomainServiceCheck
    loadBalancerType: avdHostPoolLoadBalancerType
    maxSessionLimit: avhHostPoolMaxSessions
    personalDesktopAssignmentType: avdPersonalAssignType
    tags: avdTags
    diagnosticWorkspaceId: avdAlaWorkspaceResourceId
    diagnosticLogsRetentionInDays: avdDiagnosticLogsRetentionInDays
    diagnosticLogCategoriesToEnable: varAvdHostPoolDiagnostic
  }
}

output hostPooltoken string = avdHostPool.outputs.hostPoolRestrationInfo.token
`
```
hostpool deploy.bicep:
```
`resource hostPool 'Microsoft.DesktopVirtualization/hostPools@2022-04-01-preview' = {
  name: name
  location: location
  tags: tags
  properties: {
    friendlyName: hostpoolFriendlyName
    description: hostpoolDescription
    hostPoolType: hostpoolType
    customRdpProperty: customRdpProperty
    personalDesktopAssignmentType: any(personalDesktopAssignmentType)
    preferredAppGroupType: preferredAppGroupType
    maxSessionLimit: maxSessionLimit
    loadBalancerType: loadBalancerType
    startVMOnConnect: startVMOnConnect
    validationEnvironment: validationEnvironment
    registrationInfo: {
      token: null
      expirationTime: tokenExpirationTime
      registrationTokenOperation: 'Update'
    }
    vmTemplate: ((!empty(vmTemplate)) ? null : string(vmTemplate))
  }
}
output hostPoolRestrationInfo object = hostPool.properties.registrationInfo
`
```

**Comment by danycontre** [comment]
@rickvdboor thanks for reporting the issue, we are investigating the root cause and fix.

**Comment by danycontre** [comment]
We have downgraded host pool API version to fix deployment error.

ARM/PortalUI/Bicep are back online.

We continue to investigate the issue with newer APIs so we can upgrade the version in use

**Comment by rickvdboor** [comment]
Great, let me give that a try!

**Comment by rickvdboor** [comment]
I can confirm this solves the issue.

**Comment by SvenAelterman** [comment]
> We have downgraded host pool API version to fix deployment error.
> 
> ARM/PortalUI/Bicep are back online.
> 
> We continue to investigate the issue with newer APIs so we can upgrade the version in use

Very unfortunate regression in those API versions apparently... Because the API version that supports getting the `registrationInfo` object doesn't support the `startVMOnConnect` property.
