### ISSUE TITLE
Docs section: Security, Governance and Compliance - Vulnerability scanning

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#25]
Page section: Design Recommendations
- No mention of vulnerability scanning

Fix: 

- Include guidance to use Azure Defender integrated vulnerability assessment tooling powered by Qualys Security Center's integrated vulnerability assessment solution for Azure and hybrid machines | Microsoft Docs
https://docs.microsoft.com/en-us/azure/security-center/deploy-vulnerability-assessment-vm

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
