### ISSUE TITLE
Microsoft.Compute/VirtualMachines missing extensionAadJoin

### ISSUE THREAD

**Issue by shawntmeyer** [Azure/avdaccelerator#251]
The 'avd-session-hosts-batch.bicep' sends the parameter object extensionAadJoinConfig object to the the VirtualMachine bicep to configure the AADLoginforWindows extension but the VirtualMachine bicep file doesn't contain this parameter or module.

**Comment by danycontre** [comment]
Hi @shawntmeyer the following is the flow of VM deployment for AAD join:

1. deploy-baseline.bicep calls avd-modules/avd-session-hosts-batch.bicep and passes parameter avdIdentityServiceProvider
2. avd-session-hosts-batch.bicep calls avd-modules/avd-session-hosts.bicep and passes parameter avdIdentityServiceProvider
3. avd-session-hosts.bicep calls carml/1.2.0/Microsoft.Compute/virtualMachines/deploy.bicep and passes parameter extensionAadJoinConfig
4. carml/1.2.0/Microsoft.Compute/virtualMachines/deploy.bicep calls extensions/deploy.bicep and passes the configuration for the AADLoginForWindows extension (lines 482 to 495):
module vm_aadJoinExtension 'extensions/deploy.bicep' = if (extensionAadJoinConfig.enabled) {
  name: '${uniqueString(deployment().name, location)}-VM-AADJoin'
  params: {
    virtualMachineName: virtualMachine.name
    name: 'AADLoginForWindows'
    publisher: 'Microsoft.Azure.ActiveDirectory'
    type: 'AADLoginForWindows'
    typeHandlerVersion: contains(extensionAadJoinConfig, 'typeHandlerVersion') ? extensionAadJoinConfig.typeHandlerVersion : '1.0'
    autoUpgradeMinorVersion: contains(extensionAadJoinConfig, 'autoUpgradeMinorVersion') ? extensionAadJoinConfig.autoUpgradeMinorVersion : true
    enableAutomaticUpgrade: contains(extensionAadJoinConfig, 'enableAutomaticUpgrade') ? extensionAadJoinConfig.enableAutomaticUpgrade : false
    settings: extensionAadJoinConfig.settings
    enableDefaultTelemetry: enableDefaultTelemetry
  }
}

5. extensions/deploy.bicep calls Microsoft.Compute/virtualMachines/extensions@2021-07-01 and applies the extension to the VM for AAD join and intune enrollment.

PLease let us know if additional clarification is needed.

**Comment by shawntmeyer** [comment]
correct, I forgot i opened this issue. The new PR for AADJoin and Intune covers this correctly.
