### ISSUE TITLE
Docs section: Security, Governance and Compliance - Azure Security Center (ASC)

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#26]
Page section: Design Recommendations - Azure Security Center
- Azure Security Center is mentioned however it has recently been renamed to Azure Defender for cloud. Also there is missing context as to how ESLZ assists by enforcing Azure Defender via Azure Policy on all subscriptions in scope.

Page section: Design Recommendations - Secure Score
- Microsoft Secure Score is referenced but not Azure Security Center's version

Fix:
- Update recommendation to reflect these points
- Include ASC Secure Score and context as to differences

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
