### ISSUE TITLE
Docs section: Security, Governance and Compliance - Microsoft Endpoint Manager (MEM)

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#27]
Microsoft endpoint manager is now supports AVD session hosts, but this is not referenced on the docs, we should include it.

Fix:
- Include MEM recommendations
- Update doc

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
