### ISSUE TITLE
Docs section: Security, Governance and Compliance - Patch management

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#28]
Page section: Design Recommendations - Patch Management
- Patch management is called out as important but only reference to tooling of MECM.

Fix:
- Include guidance for differences in approaches between pooled and personal host pools and suggested tooling.
- Also include other approaches like image management refreshes and host pool redeployment for pooled host pools etc.
- Update doc

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
