### ISSUE TITLE
Docs section: Security, Governance and Compliance - Endpoint protection

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#29]
Page section: Design Recommendations - Endpoint Protection

- Recommendation for endpoint protection states that "Other security needs like network protection, web content filtering, attack surface reduction, security baselines for VM hosts, and threat vulnerability management should be part of your Windows Virtual Desktop design" However in both this section and the below AVD OS Security section there is no reference to Azure Firewall or other Azure Network Security tools/practices
- The last sentence says "See the following section for links to Azure Virtual Desktop host security best practices.

Fix:
- Include guidance/suggestions for Azure Firewall (Standard/Premium) and NSGs, Service Tags, etc.
- Provide link to this section for ease of use
- Update doc

**Comment by danycontre** [comment]
- Agree with updating document to provide link for Azure Virtual Desktop host security best practices
- Azure firewall/NSG guidance in touch on the network topology and connectivity, but his subject could honestly be in any of this to sessions, so is up for team decision to pick the location

**Comment by danycontre** [comment]
![image](https://user-images.githubusercontent.com/78437433/150205569-33e47263-1db0-4d80-8c93-e23f7dc051e5.png)

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
