### ISSUE TITLE
Example file for Terraform ADDSscenario

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#292]
The AADscenario contains a tfvars.sample file.
This is great for executing a deployment and being able to see which variables need to be filled.
Are these also available for the ADDSscenario? Maybe I missed something here ;-)

**Comment by danycontre** [comment]
@jensheerin @pimvandenderen

**Comment by jensheerin** [comment]
Thank you @florian-ried for the feedback and bringing the issue. tfvars.sample added.
