### ISSUE TITLE
Cost Estimates for Deployment Scenarios

### ISSUE THREAD

**Issue by edm-ms** [Azure/avdaccelerator#3]
We should build cost estimates and diagrams for all items deployed.

**Comment by xelizondo** [comment]
Will start reviewing all Azure resources used and start with some estimations

**Comment by danycontre** [comment]
We need to find a spot for cost consideration and also where to publish the general diagram to?


Get general diagram on https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/ready?branch=collab-avd-updates

**Comment by prasad3017** [comment]
@jensheerin  @danycontre  Could you please confirm if this is still needed as a ask?

**Comment by danycontre** [comment]
@moisesjgomez checking if you were able to get some estimates.

**Comment by danycontre** [comment]
Movingn to ADO
