### ISSUE TITLE
Docs section: Security, Governance and Compliance - Diagnostics

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#30]
Page section: Design Recommendations - Enable Logging
- The reference to diagnostic logging is to log analytics workspaces is correct and good to see.

Fix:
- Advise how ESLZ framework with Azure Policies can help achieve or already perform this task for the AVD deployment.
- Update doc

**Comment by nataliakon** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207

**Comment by danycontre** [comment]
Page updated. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3207
