### ISSUE TITLE
Deploy to Azure Gov has embedded wrong locations

### ISSUE THREAD

**Issue by PowerShellCrack** [Azure/avdaccelerator#300]
The link to deploy to Azire Government does launch, but during verification it says that it is using eastus2, but I have select USGovVirigina. 

![image](https://user-images.githubusercontent.com/20599825/216708969-9662f294-a37e-4463-90f7-09d09759dc9b.png)

None of the resources are select to go back so I assume this is hardcoded in the template. If I click on Edit template on the first page, I can see that there are a few instances or eastus in template; two of them being a value (the rest is refence and examples)

![image](https://user-images.githubusercontent.com/20599825/216709606-a65432c4-6a5b-45fe-babd-e286470c3720.png)

**Comment by danycontre** [comment]
@PowerShellCrack there was a bug in the output of the portal UI that wasn't capturing the location selected so the default was being used (Bug was fixed last week), please run a new deployment and let us know the outcome.
