### ISSUE TITLE
Link to terraform broken

### ISSUE THREAD

**Issue by msdnguy** [Azure/avdaccelerator#317]
In the Image builder accelerator the link to the Terraform readme is broken.
It should point to https://github.com/Azure/avdaccelerator/tree/main/workload/terraform/customimage

It currently points to https://github.com/Azure/avdaccelerator/blob/main/workload/terraform/readme.md

**Comment by danycontre** [comment]
Thanks @msdnguy for the feedback, we are checking.

cc: @jensheerin

**Comment by jensheerin** [comment]
Thank you @msdnguy for issue! 
Links fixed
