### ISSUE TITLE
Diagram issues

### ISSUE THREAD

**Issue by thommck** [Azure/avdaccelerator#322]
The Visio diagram has two issues and one missing piece:

1. In Management Sub it says _Daskboards_ instead of _Dashboards_
<img width="335" alt="image" src="https://user-images.githubusercontent.com/29751878/227198003-dcab5c2c-0250-4bf6-9dac-5bb1d18d916f.png">
2.  There is a dot-dash purple line that is not explained on the legend
<img width="219" alt="image" src="https://user-images.githubusercontent.com/29751878/227197884-76b5f1b5-3753-4034-b03d-46474bef0cf6.png">
3. There is no Azure Bastion anywhere (used for admin access to session hosts)

**Comment by danycontre** [comment]
Diagrams updated, please let us know if you have any other feedback.
