### ISSUE TITLE
Host Pool - startVMOnConnect does not get set regardless of the setting value

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/avdaccelerator#330]
Seems there is some weirdness around API versions and host pools. 

I have to upgrade to a newer api version to get settings like startVMOnConnect to work.  But the newer api versions don't return registrationInfo object so the output property that is used to pass the token to the virtual machines fails to parse because it expects Object but gets Null.

It looks like the authors here were aware of this as they commented out the newer api. 

What is the recommended solution to make this work? How should we join session hosts to the host pool using the newer api?

![image](https://user-images.githubusercontent.com/6090341/229613756-e37c2249-f65a-4221-bbc4-fdfba1c0309c.png)
```

{
    "status": "Failed",
    "error": {
        "code": "DeploymentOutputEvaluationFailed",
        "message": "Unable to evaluate template outputs: 'hostPoolRegistrationInfo'. Please see error details and deployment operations. Please see https://aka.ms/arm-common-errors for usage details.",
        "details": [
            {
                "code": "DeploymentOutputEvaluationFailed",
                "target": "hostPoolRegistrationInfo",
                "message": "The template output 'hostPoolRegistrationInfo' is not valid: Template parameter 'hostPoolRegistrationInfo' was provided an invalid value. Expected a value of type 'Object', but received a value of type 'Null'. Please see https://aka.ms/arm-create-parameter-file for usage details.."
            }
        ]
    }
}

```

**Comment by joshuadmatthews** [comment]
I did discover that the older Hostpool API will set startVMOnConnect even though it shows as not available, so closing this ticket as this repo works as expected. I have a ticket on the ARM side to figure out why the newer modules don't work.

**Comment by danycontre** [comment]
@joshuadmatthews we are currently updating the code to use latest API for host pool creation but a previous one to get the host pool registration key, the following are some snippets:

Creating host pool:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/78437433/231206012-29ceafb2-a9ce-4e71-ab2f-e210cf164c9b.png">


Getting host pool:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/78437433/231205763-18210df1-9cd7-4732-a484-0a09973a62e6.png">
