### ISSUE TITLE
deploy-baseline.bicep deploymentPrefix minlength and default value '' (empty string with single quotes) breaks all deployment attempts

### ISSUE THREAD

**Issue by LManning-Dev** [Azure/avdaccelerator#334]
New-AzDeployment : Cannot retrieve the dynamic parameters for the cmdlet. deploy-baseline-Test.bicep(10,33) : Error BCP333: The provided value (whose length will
always be less than or equal to 0) is too short to assign to a target for which the minimum allowable length is 2.

To fix the issue and allow deployments:
change param deploymentPrefix string = '' from an empty string to either 
param deploymentPrefix string 
or 
param deploymentPrefix string = '--' 

This is despite me sending in a deployment prefix with the command. 
Bicep CLI version 0.16.1 (d77dcc750a).
The error message seems misleading. I got that with Powershell and CLI and even when there were no dynamic parameters used. 

Probably makes sense that the default value has to conform to the requirements for that parameter.

New-AzSubscriptionDeployment \`
  -TemplateFile $templateFile \`
  -TemplateParameterFile $parametersExampleFile \`
  -avdWorkloadSubsId $tier3SubscriptionId \`
  -deploymentPrefix "dep7" \`
  -avdVmLocalUserName "AzureUser" \`
  -avdVmLocalUserPassword $passwordSec \`
  -avdIdentityServiceProvider "AAD" \`
  -avdEnterpriseAppObjectId $enterpriseAppObject \`
  -avdVnetPrivateDnsZone $false \`
  -avdDeployMonitoring $true \`
  -deployAlaWorkspace $false \`
  -alaExistingWorkspaceResourceId $logAnalyticsResourceId \`
  -createAvdVnet $false \`
  -existingVnetSubnetResourceId $tier3VNET_SNET_ResourceId \`
  -avdSessionHostLocation "eastus" \`
  -avdManagementPlaneLocation "eastus" \`
  -Location "eastus" \`
  -Debug

Thank you

**Comment by danycontre** [comment]
@LManning-Dev thanks for the feedback, default value on template and parameter was updated to 'AVD1'
