### ISSUE TITLE
Alignment with Azure Landing Zones reference implementation policies

### ISSUE THREAD

**Issue by pazdedav** [Azure/avdaccelerator#352]
### Background
Many customers are adopting Azure Landing Zones [reference architecture](https://aka.ms/alz) and build their platform foundation using one of reference implementations.
When implementing AVD Accelerator in an enterprise environment that applied all [ALZ policies](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies) coming from 'Contoso reference implementation', we ran into several issues. _I wrote a detailed [blog post](https://pazdedav.blog/2023/04/21/avd-accelerator-lessons-learned/) about it if you are interested in details._

### Details
This is an overview of issues related to ALZ policies:
- [ ] Deployment Scripts are incompliant with 'Public network access should be disabled for PaaS services’ ALZ [policy](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#corp)
- [ ] Storage-Azure-Files deployment failing due to missing firewall openings (https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409, https://onegetcdn.azureedge.net/providers/providers.masterList.feed.swidtag, https://www.powershellgallery.com/*) - these should be added to 'Prerequisites' section in the implementation guide
- [ ] Custom Image Deployment - Deployment Scripts are incompliant with ALZ policy (same as above). Recommend deploying these optional components in 'Online Landing Zone' (instead of Corporate Landing Zone).
- [ ] Deployments from a CI/CD pipeline could fail at the _Automation-Account deployment_ (part of Custom Image) when attempting to enable diagnostic settings for the Automation Account to a centralized Log Analytics workspace. It is common that Workload Identities enabled for e.g., GitHub Actions workflows or Azure Pipelines have permissions scoped to a single landing zone (subscription).

### Feature request
Ensure that AVD Accelerator deployment can be compliant with 'Corporate Landing Zone' policies.

**Comment by danycontre** [comment]
@pazdedav thanks for your feedback, we are reviewing.

cc: @swathibhat1

**Comment by danycontre** [comment]
We continue to test and investigate.

**Comment by danycontre** [comment]
@swathibhat1 let's created this item in the features backlog to time the work on it.
