### ISSUE TITLE
Azure Gov API not available

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#355]
As of today, the API version 2022-09-09 for Microsoft.DesktopVirtualization is not available in Azure Government. I reverted all of the code back to API version "2022-04-04-preview" and the AVD Accelerator code still worked.

**Comment by jamasten** [comment]
I don't see "2022-04-04-preview" in my Azure US Government subscription:
![image](https://user-images.githubusercontent.com/61800683/236222244-9c128701-980f-4032-9a8b-27aaead22103.png)

**Comment by chbragg** [comment]
Oops, that was a typo on my part. The API version that I used instead of 2022-04-01-preview. I didn't bother testing with 2022-07-05-preview or 2022-08-09-privatepreview because I was only comparing the API versions with what the public Microsoft documentation showed for API version.
But the version 2022-09-09 definitely does not exist and the AVD Accelerator will not deploy using that API version in Azure Gov.

**Comment by chbragg** [comment]
Oops, that was a typo on my part. The API version that I used instead of 2022-04-01-preview. I didn't bother testing with 2022-07-05-preview or 2022-08-09-privatepreview because I was only comparing the API versions with what the public Microsoft documentation showed for API version.
But the version 2022-09-09 definitely does not exist and the AVD Accelerator will not deploy using that API version in Azure Gov.

**Comment by danycontre** [comment]
@chbragg new code was merged to use API 2022-07-05-preview when deploying to gov and API 2022-09-09 when deploying to commercial.

Please test your deployment and let us know if you have any feedback.

cc: @swathibhat1 please help us out creating the tracking item.

**Comment by chbragg** [comment]
I can't get the new version to work at all. When using the UI to "Deploy to Azure Gov" without a custom image, the deployment never creates any resources in the "HostPool-AppGroups" step. It doesn't error out, it just doesn't create the host pool or any other resource. It fails when it tries to provision the session hosts but a host pool doesn't exist.

When trying to deploy with code using Bicep, I get many errors that say "@2022-07-01" does not have types available."

Can you please revert the changes? I can see in the portal now on several different Azure Gov tenants that the API 2022-09-09 for Microsoft.DesktopVirtualization is now available.

**Comment by danycontre** [comment]
Thanks for the feedback, reverted the changes
