### ISSUE TITLE
FSLogix profiles for Azure AD-joined VMs issue

### ISSUE THREAD

**Issue by elinakh87** [Azure/avdaccelerator#361]
In the UI  AVD accelerator, when we are choosing Azure Active Directory option, Fslogix configuration still not available.
As it announce in GA, would it possible to add it?
<img width="643" alt="Screenshot 2023-05-16 181450" src="https://github.com/Azure/avdaccelerator/assets/133799767/d1a0e691-5d30-4789-b847-08dec925d241">

**Comment by danycontre** [comment]
@elinakh87 thanks for your feedback, we are working on AAD options for FSLogix and MSIX.

Is your intention to use AAD joined multi-session hosts with FSLogix and Azure files?

**Comment by elinakh87** [comment]
yes, that's correct.

**Comment by danycontre** [comment]
@elinakh87 is your customer using hybrid identities or cloud native?

**Comment by sambesselink** [comment]
We're also limited in using FSLogix for AzureAD-joined AVD. We're using cloud native Azure AD accounts.

**Comment by elinakh87** [comment]
@danycontre its cloud native as well. Any timelines we can share with the customer?

**Comment by danycontre** [comment]
@elinakh87 code as completed and is in testing under branch https://github.com/Azure/avdaccelerator/tree/aadj-fslogix-azurefiles

**Comment by danycontre** [comment]
@elinakh87 AAD+FSLogix+hybrid identities code was merged.

For cloud native identities we continue to investigate.
