### ISSUE TITLE
Permission Requirements

### ISSUE THREAD

**Issue by msdnguy** [Azure/avdaccelerator#362]
I think it would be helpful to provide the minimum permissions required to deploy the LZA.

**Comment by danycontre** [comment]
@msdnguy thanks for your feedback.

Permissions are outlined on the getting started guide: https://github.com/Azure/avdaccelerator/blob/main/workload/docs/getting-started-baseline.md#getting-started---baseline-deployment

Please let us know if more details are needed on the guide.
