### ISSUE TITLE
brown field deployment - Add session hosts in a different region 

### ISSUE THREAD

**Issue by mpchen** [Azure/avdaccelerator#368]
can we add support for adding session hosts in a different region for brown field deployment? 

Scenario - Deploy AVD management plane in one region. Then deploy session hosts in multiple regions.

**Comment by danycontre** [comment]
@mpchen thanks for the feedback, we are investigating.

**Comment by danycontre** [comment]
@swathibhat1 let's created this item in the features backlog to time the work on it.
