### ISSUE TITLE
Session hosts getting DomainTrustCheck and DomainJoinedCheck with AAD

### ISSUE THREAD

**Issue by mpchen** [Azure/avdaccelerator#369]
When session hosting joining AAD, I am getting two errors: DomainTrustCheck and DomainJoinedCheck. 
All other stacks can be deployed successfully. 

This seems to be a new issue since the stack I deployed 3 days ago was working perfectly. Any recent commits/changes that could possibly cause this? Thanks.

**Comment by danycontre** [comment]
@mpchen thanks for the feedback, we are investigating.

**Comment by danycontre** [comment]
@mpchen just ran a test deployment and had no issues with AAD: 
<img width="862" alt="image" src="https://github.com/Azure/avdaccelerator/assets/78437433/f663a38b-fabc-40de-a4e6-ff7d3c75226a">

<img width="869" alt="image" src="https://github.com/Azure/avdaccelerator/assets/78437433/b542167c-51c3-46a0-89db-c0824bfef6cc">


Did something change in your environment?

**Comment by mpchen** [comment]
Thanks @danycontre for the quick response. May I ask which image you use for session host? I use Windows11 2H multi session with Office 365. Would like to try a different one to see whether it is caused by the image.
