### ISSUE TITLE
Add region to session hosts naming 

### ISSUE THREAD

**Issue by mpchen** [Azure/avdaccelerator#372]
Currently session VM naming is "vm-avd-rapp-00x".

When using the template in multiple regions, the new VMs in the 2nd or 3rd region won't be able to register with AAD since the hostname is already taken. For more details, check #369 

Would be great if we can add region or some random strings to VM naming.

**Comment by danycontre** [comment]
@mpchen thanks for the feedback we are reviewing.

**Comment by danycontre** [comment]
Session host naming schema was changed to include deployment environment and region: vm<deloymentPrefix><environment><locationAchronym>####

Example: vmt058deus20001
