### ISSUE TITLE
AVD Alerts Bug: Deployment Script Fails on Host Pool using Private Link

### ISSUE THREAD

**Issue by jamasten** [Azure/avdaccelerator#379]
My customer receives an "Authorization Failure" since their host pool is not publicly accessible and hidden behind the private link service.

This solution will most likely need to deploy a VM in the VNET / Subnet containing the endpoint for the host pool to collect the required data, instead of using a deployment script.

**Comment by JCoreMS** [comment]
Great point as this will impact the upcoming Private Link options for Host Pools.  This sounds like we may need to request the PG to provide an option for deployment scripts to include network settings for the container and/or possibly utilize a Server OS or alternate VM to run the script from a trusted VNet/subnet.  Additional testing and plans to add this coming.

**Comment by JCoreMS** [comment]
Waiting to confirm but should be fixed with v2.1.0.
