### ISSUE TITLE
Bug report: wrong file name in deploy-baseline.bicep

### ISSUE THREAD

**Issue by kedar-1** [Azure/avdaccelerator#390]
Hello,

is there someone who is using this repo in real life for deployment?

CI build is failing about month back so its impossible to deploy the code :-(

The reason is obvious: workload/bicep/deploy-baseline.bicep looks for "storageAzureFiles" but only StorageAzureFiles exist.

Thanks for fix

**Comment by danycontre** [comment]
@kedar-1 thanks for you feedback.

Most of deployments are using ARM/Portal UI built from Bicep, but we do run tests from Bicep and they were not failing even though as you pointed out the folder naming was wrong (not the ideal behavior).

Folder name was updated and we made sure changes were synced and taken (sometimes git is not good with caption updates).

Please sync your code, test again and let us know the outcome.

**Comment by kedar-1** [comment]
Hmm, bug report closed but the error persist, CI build #904:

/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(916,36) : Error BCP091: An error occurred reading file. Could not find a part of the path '/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/modules/identity/deploy.bicep'.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(968,9) : Error BCP062: The referenced declaration with name "managedIdentitiesRoleAssign" is not valid.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1079,72) : Error BCP062: The referenced declaration with name "managedIdentitiesRoleAssign" is not valid.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1092,33) : Error BCP104: The referenced module has errors.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1110,63) : Error BCP062: The referenced declaration with name "managedIdentitiesRoleAssign" is not valid.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1135,30) : Error BCP104: The referenced module has errors.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1153,63) : Error BCP062: The referenced declaration with name "managedIdentitiesRoleAssign" is not valid.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/deploy-baseline.bicep(1216,74) : Error BCP062: The referenced declaration with name "managedIdentitiesRoleAssign" is not valid.
/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/modules/storageAzureFiles/deploy.bicep(191,31) : Error BCP091: An error occurred reading file. Could not find file '/home/runner/work/avdaccelerator/avdaccelerator/workload/bicep/modules/storageAzureFiles/.bicep/azureFilesDomainJoin.bicep'.
Error: Process completed with exit code 1.
