### ISSUE TITLE
Feedback Request: Provide a Template to Deploy AVD Deep Insights Workbook

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#393]
Hey Team, I think it would help if you could potentially create a template/templateSpec version of the AVD Deep Insights workbook, so you can specify the **Log Analytics Workspace** during the deployment.  You could add Sub/RG as well.  I think it's convenient for customers to have a central location for their Workbooks within the AVD Blade.  Kind of like how the AVD Insights works.

Here's an example:

![image](https://github.com/Azure/avdaccelerator/assets/26752719/64462d20-0fa1-47e8-a0cf-d22b07a29f10)

**Comment by danycontre** [comment]
@brmcmill agree it would be good to incorporate additional workbooks or links to them.

Are you referring to this workbook https://blog.itprocloud.de/AVD-Azure-Virtual-Desktop-Error-Drill-Down-Workbook/ ?

**Comment by danycontre** [comment]
@swathibhat1 let's created this item in the features backlog to time the work on it.
