### ISSUE TITLE
Bug report: Why is temporary VM created from Custom Image gallery?

### ISSUE THREAD

**Issue by kedar-1** [Azure/avdaccelerator#401]
Hello,

we have provided a Template URI for the Sessions host deployment to use customized image.

After the change all deployments fail because the temporary VM has been provisioned using the SAME Template URI as the Session hosts.

As we have create a Templete TrustedLunch enabled and Temporary VM has no section about Security type in place the only way is to patch bicep deployment to accept Security Type.

Please explain the reason for using the same Image for non session host deployment.

Thanks

Radek

**Comment by moisesjgomez** [comment]
Hi Radek, thanks for your feedback. Working on the fix for this to include security type on the temporary VM and use marketplace image.

**Comment by danycontre** [comment]
@kedar-1 PR was merged to differentiate settings of session hosts from mgmt VM settings, now all VMs share the same security settings but mgmt and session hosts have different source image, size, among other settings.

PR: Mgmt vm updates #408
