### ISSUE TITLE
Issue Portal UI | Cant select Groups under "Azure Virtual Desktop access assignment"

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#406]
In the past, you could type in any object ID. That was great. Now a group must be selected from a drop down. Only about 50 groups are displayed. Searching for groups does not work. The error occurs with several tested independent tenants.
<img width="1118" alt="image" src="https://github.com/Azure/avdaccelerator/assets/95634472/b031a860-e88c-4b46-b52e-e0a565ad0856">

**Comment by danycontre** [comment]
@florian-ried thanks for your feedback, we updated the portal UI to include both options for selecting/entering groups:
