### ISSUE TITLE
[Issue] Portal-UI Storage Account Quota 

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#409]
In the Azure Portal UI scenario, the size of the file share is set to 1000 GB after successful deployment.
And this despite the fact that 100 GB was configured.

<img width="1028" alt="image" src="https://github.com/Azure/avdaccelerator/assets/95634472/023f126d-6540-4f9a-809f-000fac521cdf">

**Comment by danycontre** [comment]
@florian-ried please try again a fix was pushed recently.
