### ISSUE TITLE
[Feedback Request] Portal-UI | Support Trusted Launch for MGMT-VM

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#410]
If a gallery image is used in the portal UI rollout that has Trusted Lunch enabled, the creation of the MGMT VM fails because it does not support Trusted Launch. Would be great if this is supported in the future so that full deployment with Trusted Launch is possible.

**Comment by danycontre** [comment]
@florian-ried a PR was merged recently to use a different source image for the mgmt VM and apply the same security settings of the session hosts to it.

**Comment by moisesjgomez** [comment]
@florian-ried may you provide the inputs of that MGMT-VM-XX deployment?

**Comment by florian-ried** [comment]
Of course :) 

[inputs.zip](https://github.com/Azure/avdaccelerator/files/11918063/inputs.zip)
