### ISSUE TITLE
[Feedback Request] Documentation of detailed permissions Domain Join User

### ISSUE THREAD

**Issue by florian-ried** [Azure/avdaccelerator#411]
I've noticed that there's a need for a detailed documentation on the required permissions for the Domain Join User in a classic Active Directory (AD DS) scenario, specifically for successful deployment and domain joining of the Storage Account.

I found that when the Active Directory User is only granted permission to create computer accounts in the OU, the script "https://github.com/Azure/avdaccelerator/blob/main/workload/scripts/DSCStorageScripts/script-domainjoinstorage.ps1" fails to execute properly. However, when the Active Directory User temporarily receives "Domain Admin" rights, the script runs successfully and the Active Directory configuration for the Storage Account is correctly implemented.

It would be fantastic if the documentation could provide detailed information on the permissions that need to be granted to this user.

**Comment by moisesjgomez** [comment]
@florian-ried thank you for your feedback. We will add clarity to this.

**Comment by danycontre** [comment]
@swathibhat1 let's created this item in the features backlog to time the work on it.
