### ISSUE TITLE
Typo on AVD Alerts brownfield deploy

### ISSUE THREAD

**Issue by Bennzn** [Azure/avdaccelerator#425]
Hi, 
seems there is a typo in the deploy.bicep file of AVD Alerts:
![image](https://github.com/Azure/avdaccelerator/assets/49479954/1f9886b3-01dd-45f9-ae0c-19ef2dd3c119)

Therefore the deployment fails:
![image](https://github.com/Azure/avdaccelerator/assets/49479954/3112cec9-ecab-43f8-99d6-b3749b5ff8e7)

btw:
thanks for the great work!

Regards,
Ben

**Comment by danycontre** [comment]
@Bennzn thanks for reporting the issue.

cc: @JCoreMS

**Comment by danycontre** [comment]
@Bennzn parameter was updated to PT5M.

Waiting for @JCoreMS confirmation on the value.

**Comment by danycontre** [comment]
@JCoreMS confirmed the right value is PT5M.

THanks @Bennzn for reporting the issue, changes were applied.
