### ISSUE TITLE
Question: Where to find log file from StorageDomain Join?

### ISSUE THREAD

**Issue by kedar-1** [Azure/avdaccelerator#427]
Hello, 

in DSCStorageScripts/Configuration.ps1 I see lines with code:
                 Write-Log "Successfully domain joined and/or NTFS permission set on Storage account"

Where I can find the log files with all records from the script?

I'm able to find DSC section in Event Viewer but the records from the scripts are not there.

Thanks

R.

**Comment by danycontre** [comment]
@kedar-1 

The logs for the domain join execution are located at: C:\Windows\Temp\ManualDscStorageScriptsLog.log (defined by the Logger.ps1 script).

Which identity service provider are you using?

**Comment by kedar-1** [comment]
Hi @danycontre 

thanks for a quick answer, log file is in place :-)
We are using on-prem AD DS.

I see a succesfull info about storage account
07-14-23 20:58:11 - MSFT_ScriptResource:69 - Turning off Windows firewall. 
07-14-23 20:59:28 - MSFT_ScriptResource:80 - Installing AzFilesHybrid module
07-14-23 21:22:20 - MSFT_ScriptResource:101 - Storage account xxxxxxxxxxx is already domain joined.
07-14-23 21:22:20 - MSFT_ScriptResource:20 - Successfully domain joined and/or NTFS permission set on Storage account

But in Azure portal there is no info about Domain under Active Directory section for FSlogix file share :-(
Maybe its related to #411? 


Thanks

R.

**Comment by danycontre** [comment]
Thanks for the feedback, we are checking.

**Comment by danycontre** [comment]
@kedar-1 we will follow the identity discussion on item #411
