### ISSUE TITLE
Bug: ZT Key Vault deployment

### ISSUE THREAD

**Issue by jensheerin** [Azure/avdaccelerator#430]
Steps to reproduce:
Select ZT option during deployment. 
Results in 2 key vaults created - 2nd key vault has zt in the name with nic and PE resources.

**Comment by danycontre** [comment]
@jensheerin thanks for your feedback.

Current code creates 2 keyvaults when ZT is enabled, the keyvaults are:

- Workload keyvault:
   - Name: kv-<deploymentPrefix>-<environment>-<regionAchronim>-<4CharRandomString>
   - Purpose: store deployment credentials (domain join and local admin) as secrets
- ZT keyvault:
   - Name: kv-zt-<deploymentPrefix>-<environment>-<regionAchronim>-<4CharRandomString>
   - Purpose: store disk encryption key

Please let us know if above wasn't the case for your deployment, happy to further check and assist.

@jamasten Jen brings fair concerns about the additional cost of another keyvault and private endpint, let's discuss options/impact of consolidate in just one keyvault for credentials plus ZT.

**Comment by jamasten** [comment]
@danycontre @jensheerin
Hey team, Jen and I discussed this before I implemented the code.  The reason we are using 2 key vaults was based on ZT principles.  The documentation states that RBAC isolation is not enough for Azure resources.  Having a separate key vault with a private endpoint allows network isolation on top of the separation of duties. Private endpoints are charged based on egress traffic right? How is there a cost difference between having 1 or 2 key vaults if the network egress is the same? I'm happy to dig into this more to find a happy, cost effective solution for our customers.

**Comment by jamasten** [comment]
Also, from a gov perspective, typically a COMSEC custodian manages the keys and should not have access to anything but the keys in a key vault.

**Comment by jensheerin** [comment]
Let's discuss https://learn.microsoft.com/en-us/azure/key-vault/general/best-practices#use-separate-key-vaults

**Comment by jensheerin** [comment]
Could we improve the naming convention of the key vault to reflect the purpose e.g. secrets and keys.

**Comment by danycontre** [comment]
@swathibhat1 let's created this item in the features backlog to time the work on it.
