### ISSUE TITLE
AVD Alerts: Issue with Memory Alerts Firing Off on VMs Scaling or Newly Deployed

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#439]
Hey Team -- one issue we have observe with the alerts is the VM Memory Alerts will fire off if a VM is turned on via Auto-Scaling or is a newly deployed VM.  This causes unnecessary alerts for customers.  We should see if it's possible to provide an alert for only VMs that have been turned on and in use where the Memory spikes.  This will provide better awareness for customers to make decisions on those Alerts.  Hope this helps!

**Comment by danycontre** [comment]
@brmcmill thanks for your feedback, we are checking.

@JCoreMS

**Comment by danycontre** [comment]
Updates pushed to alerts code.

**Comment by JCoreMS** [comment]
@brmcmill let me know if this change in the alerts for memory and cpu for v2.1.2 helps resolve this issue.
