### ISSUE TITLE
Deployment Name over 64 Chars - RG and HP names long

### ISSUE THREAD

**Issue by JCoreMS** [Azure/avdaccelerator#454]
As noted per Jason Masten, the deployment for customers where the host pool names are in excess of 25 characters and in addition to the alert names which are being combined during deployment, it will fail if these are in excess of 64 characters.  

In an effort to preserve some names during deployment in order to make troubleshooting easier, avoided creating GUID based names.

Need to investigate a way to mitigate this so users with long Resource Group and Host Pool names do not prevent deployment from completing successfully.

**Comment by moisesjgomez** [comment]
@JCoreMS Thank you for looking into this issue. We are reviewing your PR and will inform you once merged. Thank you!
