### ISSUE TITLE
ARM template deployment error

### ISSUE THREAD

**Issue by eversonamancio** [Azure/avdaccelerator#459]
I used the Deploy to Azure option to deploy the baseline template and get the following error message joining Azure Files to domain, even using the correct credentials.

VM has reported a failure when processing extension 'AzureFilesDomainJoin' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: "Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'The user name or password is incorrect
    + CategoryInfo          : AuthenticationError: (:) [], CimException
    + FullyQualifiedErrorId : Win32Error:1326
    + PSComputerName        : localhost
![AVD_Template_Deployment_Error](https://github.com/Azure/avdaccelerator/assets/21272021/43120a6b-5151-4d7e-8a0b-253ed0a47727)

**Comment by danycontre** [comment]
@eversonamancio thanks for reporting the issue, we are running tests and will get back to you.

**Comment by danycontre** [comment]
@eversonamancio please take a look at the storage domain join script inside your management VM at: C:\Windows\Temp\ManualDscStorageScriptsLog.log

If using custom DNS servers and/or private endpoints, please make sure that the management VM can resolve your domain name and the storage account FQDN to the private IP on the private endpoint.

**Comment by eversonamancio** [comment]
Hi Dany,

I just clicked on Deploy to Azure button and followed the process to deploy AVD so I couldn't identify the management VM you mentioned.

In my test I didn't deploy a private endpoint.

[A screenshot of a computer  Description automatically generated]

Everson Amancio
Celular: +55 11 976959913
Twitter/Skype/LinkedIn: eversonamancio

**Comment by danycontre** [comment]
@eversonamancio the deployment process creates a service objects resource group and a management VM, so even though the deployment didn't complete, the management resources were created, you can connect to the VM to look for the logs i referenced.

The resources names are:
- Resource group: rg-avd-<DeploymentPrefix>-<Environment>-<Region>-service-objects
- Management VM: vmmgmt<DeploymentPrefix><Environment><Region>

The log is located inside the management VM at: C:\Windows\Temp\ManualDscStorageScriptsLog.log

**Comment by eversonamancio** [comment]
Excellent! I'm gonna check it out.

Thanks.

Everson Amancio
Celular: +55 11 976959913
Twitter/Skype/LinkedIn: eversonamancio

**Comment by eversonamancio** [comment]
> @eversonamancio the deployment process creates a service objects resource group and a management VM, so even though the deployment didn't complete, the management resources were created, you can connect to the VM to look for the logs i referenced.
> 
> The resources names are:
> 
> * Resource group: rg-avd----service-objects
> * Management VM: vmmgmt
> 
> The log is located inside the management VM at: C:\Windows\Temp\ManualDscStorageScriptsLog.log

@danycontre I connected to the management VM, but there is no log file named ManualDscStorageScriptsLog.log in this VM.

**Comment by danycontre** [comment]
@eversonamancio what is the identity service provider you are using (AAD, AADDS, ADDS)?

If using ADDS or AADDS, w=once you log into the management VM please make sure the VM can resolve your domain name and that it has line of site to your domain controllers.

**Comment by danycontre** [comment]
Closing this item, no reply from requestor.
