### ISSUE TITLE
Management VM domain join extension error - even though I can manually join it to my domain

### ISSUE THREAD

**Issue by DaniMathews** [Azure/avdaccelerator#460]
Hello team, my portal deployment repeatedly fails at the VM domain join extension on the storage management VM. I had successfully run the deployment twice before with the same setup and settings and now I can't get passed this extension error. 

I have my DC on a VM in another vNet and peering has worked successfully.

To troubleshoot I built a test VM to connect the storage management VM and test it's connectivity to the DC - and also check the credentials for domain join. I can successfully join the management VM to the domain using the credentials and DNS IP I used in the deployment. 

Could you please help me understand where to find detailed error logs for the extension error? At the moment I just get this:

VM has reported a failure when processing extension 'DomainJoin' (publisher 'Microsoft.Compute' and type 'JsonADDomainExtension'). Error message: "Exception(s) occurred while joining Domain '******.com'". More information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot.  (Code: VMExtensionProvisioningError)

**Comment by danycontre** [comment]
@DaniMathews we are running some tests and will get back to you.

**Comment by danycontre** [comment]
@DaniMathews please check the following error log inside the management VM: C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.JsonADDomainExtension\1.3.11\ADDomainExtension.log

**Comment by DaniMathews** [comment]
Thank-you - the management VM completed successfully because I've now manually joined it but the pool VM's failed with error 1323 - I added the domain name to the username for domain join and now it's working. I could've sworn I didn't use this format yesterday when it worked but logic says I didn't!

Appreciate the quick response, I can now move on to my next steps.

Kind Regards
Daniella
________________________________

**Comment by danycontre** [comment]
@DaniMathews thanks for the updates, please let us know if additional assistance is required.
