### ISSUE TITLE
AVD Alerts Feature Request: Create an Alert to Email the "User" when their Profile is Full

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#462]
Hey Team!  This would be an immensely beneficial feature if you could create an alert to email the user who is impacted by the FSLogix Profile Disk being full.  Users often do not know why they run into space issues until they contact an AVD admin to investigate.  Hope this helps!

**Comment by danycontre** [comment]
@JCoreMS tagging you on this one for visibility.

@swathibhat1 please create an item to track this one as new feature request.

**Comment by swathibhat1** [comment]
[like]  Swathi Bhat reacted to your message:
________________________________
