### ISSUE TITLE
How can I deploy additional session hosts to the hostpool?

### ISSUE THREAD

**Issue by cchen-hrp** [Azure/avdaccelerator#463]
Can I use the baseline template to deploy additional session hosts to the host pool? Or there is a brown field deployment template  I should use? Thanks.

**Comment by danycontre** [comment]
@cchen-hrp we are working on a brownfield scenario to add additional session hosts but is not available yet.

In the meantime, you can use the session hosts module (workload/bicep/avdSessionHosts/deploy.bicep) to deploy additional session hosts to the host pool, use the count index (countIndex) parameter to continue the session hosts naming count.
