### ISSUE TITLE
Custom AVD Deployment using Azure GUI - issues and fixes

### ISSUE THREAD

**Issue by jmatveyev** [Azure/avdaccelerator#469]
Several issues found and remediated manually

1. when selecting a VMsize note that this for some reason only deploys to zone 3 and the default vmsize did not match for me. I had to manually change it in the template. 

2. Microsoft depreciated retention policies. to resolve the errors you will get when it tries to create automation account diagnostic settings. Fix: Set retention policies to false on lines 5777, 5790, 8026, and 8039 in the template, also remove the 30 days parameter value for log analytics workspace retention within the parameters file

Hope this helps someone

**Comment by jmatveyev** [comment]
FYI, these issues are still in the template.

**Comment by danycontre** [comment]
@jmatveyev thanks for reporting the issues.

Comments:
1. What is the region you are deploying to? please make sure the VM SKU is available in the region or on the availability zones you are planning to use.
2. Retention was removed from the diagnostic settings of resources, please try again.

**Comment by danycontre** [comment]
Closing this one, no reply from requestor.
