### ISSUE TITLE
AVD Landing Zone Accelerator Deployment error - storage-fslogix

### ISSUE THREAD

**Issue by jmatveyev** [Azure/avdaccelerator#471]
"Diagnostic settings does not support retention for new diagnostic settings."

need to know which specific lines need to be set to false to bypass this.

![iScreen Shoter - Microsoft Teams - 230907164205](https://github.com/Azure/avdaccelerator/assets/143737354/a6f24cbf-9479-4b38-9c5f-f330c2de7a58)

**Comment by danycontre** [comment]
@jmatveyev thanks for reporting the issue, we are checking it.

Are you using existing or new log analytics workspace?

@moisesjgomez

**Comment by jmatveyev** [comment]
Existing workspace

**Comment by jmatveyev** [comment]
I can also tell you that Setting the following lines in the template to "false" did not solve the problem. There is more to it.

Line 41451, 41464, 37197, 37210

**Comment by j-d-harvey** [comment]
Looks like I submitted a duplicate issue. Ran into this myself recently and it is due to a change a couple of weeks ago:

https://github.com/Azure/ResourceModules/issues/3572

To fix under Microsoft.Insights/diagnosticSettings in the Logs section set:

    retentionPolicy: {
      enabled: false
      days: 0
    }

**Comment by danycontre** [comment]
@j-d-harvey thanks for the testing and insights we are checking diagnostic settings on all resources to apply a fix.

We will be closing your issue as we are working on the same topic on this one.

**Comment by jmatveyev** [comment]
Hi, just following up for a status update?

**Comment by DenisBalan** [comment]
Any ETA? as we are affected as well.
Thx
