### ISSUE TITLE
Diagnostic Settings Failing to Deploy - Retention Settings Need To Be Disabled

### ISSUE THREAD

**Issue by j-d-harvey** [Azure/avdaccelerator#473]
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Diagnostic settings does not support retention for new diagnostic settings."
    }
}

This is due to a recent change. To fix under Microsoft.Insights/diagnosticSettings in the Logs section set:

        retentionPolicy: {
          enabled: false
          days: 0
        }

**Comment by danycontre** [comment]
@j-d-harvey thanks for reporting the issue we are working on it for issue #471
