### ISSUE TITLE
PolicyInsights resource provider error

### ISSUE THREAD

**Issue by wcneumann219** [Azure/avdaccelerator#475]
The script appears to need the micsrosoft.policyinsights resource provider, but when using a subscription that doesn't have it set, the script errors out. However, in the aftermath, the script did register that resource provider.

I'd like to suggest that the script review process check for resource provider registrations BEFORE executing the script.

**Comment by moisesjgomez** [comment]
@wcneumann219 Thank you for bringing this to our attention. We are investigating it.

**Comment by moisesjgomez** [comment]
@swathibhat1 Please add this item to the backlog for new feature to the LZA.
