### ISSUE TITLE
Script doesn't tolerate VMs being present from prior executions...

### ISSUE THREAD

**Issue by wcneumann219** [Azure/avdaccelerator#476]
If one encounters and fixes an error when running the script for the first time, and then runs the script again, it will not run if any of the hosts or management VMs are present. The error suggests that one is trying to change the admin password on those servers.

To work around this we had to delete the VMs (and their counterparts in our Windows AD OU) and try again.

The deployment steps for the script should point out what things need to be deleted in order to "re-run" this script after fixing any errors.

**Comment by jamasten** [comment]
@wcneumann219 did you disable the scaling plan and ensure all the VMs are online?  VM extensions cannot perform update deployments if the VMs are not online.

**Comment by danycontre** [comment]
Closing this one, no reply from requestor.

Thanks @jamasten for checking it out.
