### ISSUE TITLE
AVD LZA Error - SH-Batch-0-20230912T181224Z

### ISSUE THREAD

**Issue by jmatveyev** [Azure/avdaccelerator#478]
Please check that at least one image has been replicated to eastus2 or that the ‘exclude from latest’ flag is set to false.

I used an image gallery that was created using the baseline deployment here. I don't see the flag it is referring to in the template. 

![image](https://github.com/Azure/avdaccelerator/assets/143737354/bf5fdeab-11d0-4f37-8e3a-d5568ccd06cc)

![image](https://github.com/Azure/avdaccelerator/assets/143737354/cc230c9a-c7da-4b55-85c7-5c83f1337399)

**Comment by danycontre** [comment]
@jmatveyev thanks for reporting the issue.

To better understand your setup, you use the custom image deployment to create an image in East US 2 and then try deploying the AVD LZA baseline in the same region using the created custom image as source?

**Comment by jmatveyev** [comment]
yes, that is correct.

**Comment by danycontre** [comment]
We are checking and will keep you updated.

**Comment by danycontre** [comment]
@jmatveyev we were not able to replicate the issue you are having; please make sure the image you are trying to use is available a the region you are deploying to.

**Comment by danycontre** [comment]
We were not able to get a reply from requerstor.
