### ISSUE TITLE
Leverage AutoPilot to deliver custom configuration task sequences to AVD

### ISSUE THREAD

**Issue by Shreyabakshi712** [Azure/avdaccelerator#480]
Typically AutoPilot uses hardware IDs to accomplish this however having the option to not need to create an image but rather have a task sequence deploy based on the machine time

**Comment by moisesjgomez** [comment]
@Shreyabakshi712 Thanks for raising this. Looking to better understand the issue. Would you be able to provide me with more information and/or context to understand the request better? Thank you!

**Comment by Shreyabakshi712** [comment]
Reached out to the customer, waiting to get more details

**Comment by danycontre** [comment]
Moving to ADO as an enhancement feature request.

cc: @moisesjgomez @swathibhat1
