### ISSUE TITLE
Feedback: Text Dialog Box for VM Size Selection with Guidance

### ISSUE THREAD

**Issue by JCoreMS** [Azure/avdaccelerator#484]
Consider adding a text box above VM Size / SKU selection to possible provide quick reference to AVD Sizing guidelines:
https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/virtual-machine-recs

"For additional guidance on sizing your VM click here."

**Comment by danycontre** [comment]
@JCoreMS thanks for the feedback, we added an infobox with the VM sizing information. 

![image](https://github.com/Azure/avdaccelerator/assets/78437433/e232ee16-afab-4cb7-8a43-63cdf7073da9)
