### ISSUE TITLE
Diagnostic Settings Storage Retention failure, related with automation account

### ISSUE THREAD

**Issue by matiasma** [Azure/avdaccelerator#485]
based on the Diagnostic Settings Storage Retention feature deprecation (https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabs=portal), we need to update the "diagnosticLogsRetentionInDays", from 30 (current value) to 0, to avoid deployment error related with automation account provisioning.

line 7696 of the file workload/arm/deploy-custom-image.json

**Comment by jamasten** [comment]
Thank you @matiasma for reporting this issue.  We have fixed the bicep code but have failed to compile the JSON for that solution.  We'll make the update today.
