### ISSUE TITLE
Azure Gov Zero Trust Bug

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#512]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying with bicep and with the diskZeroTrust value set to "true", I get an error that says, "ResourceIdentity Type must be provided and set to 'SystemAssigned'.". When deploying to Azure Commercial with the exact same parameters, I don't get that error. The step where the error occurs is when the "Disk Encryption Set" is being provisioned

### Please provide the correlation id associated with your error or bug.

12763fb9-69ed-4d1a-8f67-39976da85d6c

### What was the expected outcome?

A disk encryption set gets provisioned in the Azure Gov cloud

**Comment by danycontre** [comment]
@Benwcloudnexus thank you for reporting the issue, we are checking.

**Comment by danycontre** [comment]
@swathibhat1 let's create an item on the backlog to work this feature.

@chbragg we will work on the issue internally as it requires Gov cloud testing.

cc: @jamasten
