### ISSUE TITLE
Storage Account domain join

### ISSUE THREAD

**Issue by Benwcloudnexus** [Azure/avdaccelerator#513]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Deploying landing zone with Azure AD Domain services with FSLogix fails to complete due to an issue with a missing parameters on the script used to join the storage account. 

### Please provide the correlation id associated with your error or bug.

93083771-d0fb-40b9-b496-82ef060a385e

### What was the expected outcome?

Storage account joins to domain and deployment completes. 

### Relevant log output

```Shell
VM has reported a failure when processing extension 'AzureFilesDomainJoin' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: "Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.15\Downloads\0\Manual-DSC-Storage-Scripts.ps1 : A 
positional parameter cannot be found that accepts argument 'AVD'.
    + CategoryInfo          : InvalidArgument: (:) [Manual-DSC-Storage-S...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.  (Code: VMExtensionProvisioningError)
```

**Comment by danycontre** [comment]
@Benwcloudnexus thank you for reporting the issue, we are checking.

**Comment by danycontre** [comment]
@ManzAlam91 @Benwcloudnexus there was a bundle of updates to the storage setup 

We were not able to reproduce the issue deploying form current code, please check the description of this PR: https://github.com/Azure/avdaccelerator/pull/506

If you are deploying from a fork/clone of this repo, please sync changes from Azure main or update the deployment template to use your version of the script/packages.

The following are the lines that will need to be updated to use your files:
- file: avdaccelerator\workload\bicep\deploy-baseline.bicep
- lines (pointing to Azure/main by default):
  - 540: var varBaseScriptUri = 'https://raw.githubusercontent.com/Azure/avdaccelerator/main/workload/'
  - 756: var varStorageAzureFilesDscAgentPackageLocation = 'https://github.com/Azure/avdaccelerator/raw/main/workload/scripts/DSCStorageScripts.zip'

Please let us know if further assistance is needed.

**Comment by Benwcloudnexus** [comment]
thanks @danycontre  i will take another look at this when I can. To confirm i deployed directly from this repo.

**Comment by danycontre** [comment]
Thanks for the updates, let us know how we can assist.
