### ISSUE TITLE
Session Host configuration fails to complete due to script error

### ISSUE THREAD

**Issue by Benwcloudnexus** [Azure/avdaccelerator#514]
### What happened? Provide a clear and concise description of the bug, including deployment details.

when deploying using Azure AD Domain services, no FSLogix profile managment, the SessionHostConfiguration.ps1 failed to complete on the sessions hosts due to a missing parameter. 

### Please provide the correlation id associated with your error or bug.

65f76281-bf0a-4706-bbd1-456aa5f2a41f

### What was the expected outcome?

session hosts configuration completed and deployment moves on. 

### Relevant log output

```Shell
M has reported a failure when processing extension 'SessionHostConfig' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: "Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.15\Downloads\0\Set-SessionHostConfiguration.ps1 : 
Missing an argument for parameter 'IdentityDomainName'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo     ...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.  (Code: VMExtensionProvisioningError)
```

**Comment by danycontre** [comment]
@Benwcloudnexus thank you for reporting the issue, we are checking.

**Comment by danycontre** [comment]
@ManzAlam91 @Benwcloudnexus there was a bundle of updates to the storage setup 

We were not able to reproduce the issue deploying form current code, please check the description of this PR: https://github.com/Azure/avdaccelerator/pull/506

If you are deploying from a fork/clone of this repo, please sync changes from Azure main or update the deployment template to use your version of the script/packages.

The following are the lines that will need to be updated to use your files:
- file: avdaccelerator\workload\bicep\deploy-baseline.bicep
- lines (pointing to Azure/main by default):
  - 540: var varBaseScriptUri = 'https://raw.githubusercontent.com/Azure/avdaccelerator/main/workload/'
  - 756: var varStorageAzureFilesDscAgentPackageLocation = 'https://github.com/Azure/avdaccelerator/raw/main/workload/scripts/DSCStorageScripts.zip'

Please let us know if further assistance is needed.

**Comment by Benwcloudnexus** [comment]
thanks @danycontre i was deploying direct from this repo, ill give it another go when i get the opportunity.
