### ISSUE TITLE
[PLACEHOLDER] - Place a descriptive title here

### ISSUE THREAD

**Issue by alpesh-exigotech** [Azure/avdaccelerator#519]
Hello there,

I am getting below error while creating resource group through Bicep script. How to resolve this error?

![image](https://github.com/Azure/avdaccelerator/assets/88418557/840779c2-c779-4c39-95fb-b8fc818dfca8)

**Comment by danycontre** [comment]
@alpesh-exigotech thanks for reporting the issue.

The deployment that is failing for you is trying to grant AVD enterprise application access to your pool compute and service objects, this is used by the scaling plan and start VM on connect features.

Please make sure that your Microsoft Entra ID tenant has the following app ID:
- Name: could be Azure Virtual Desktop or Windows Virtual Desktop
- AppID: 9cdead84-a844-4324-93f2-b2e6bb768d07

If you don't have it on you Entra ID tenant, please check if the Microsoft.DesktopVirtualization resource provider has been registered in a subscription connected to the tenant.

![image](https://github.com/Azure/avdaccelerator/assets/78437433/f051662f-7b27-47cd-a53f-dace28029bd7)

**Comment by alpesh-exigotech** [comment]
Thank you @danycontre for your guidance. I found that Microsoft.DesktopVirtualization was not registered in my subscription. 

After registering it I start getting below error with few successful resource deployments. Can you please let me know what I am missing here.

![image](https://github.com/Azure/avdaccelerator/assets/88418557/e2e9c08c-35c2-452a-b5a7-ce401e1ee910)

**Comment by danycontre** [comment]
@alpesh-exigotech please go inside the AVD-MGMT-Plane* deployment and share the details of the internal deployment that failed.

**Comment by alpesh-exigotech** [comment]
@danycontre 

Are you referring this one ? 

![image](https://github.com/Azure/avdaccelerator/assets/88418557/732265c8-e204-47ed-8452-97aae91303e7)

**Comment by danycontre** [comment]
@alpesh-exigotech checking if you are still having this issue?

Did you select a group to be granted access to AVD resources?

**Comment by alpesh-exigotech** [comment]
Hi @danycontre 

Thanks for follow up. Yes, I selected group access and it's working. However, I am facing some issues with Private DNS, and I believe that's it related to open issue https://github.com/Azure/bicep/issues/9839 with this. Please correct me if I am referring to older or different issues. For now, I am closing this issue and will open another one for Private DNS.
