### ISSUE TITLE
Active Directory Group Names cannot contain spaces

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/avdaccelerator#520]
### What happened? Provide a clear and concise description of the bug, including deployment details.

AD domain join for storage account fails if AD group name contains a space.

### Please provide the correlation id associated with your error or bug.

fd8acacd-9b07-4df3-bdaf-83ec2bb2c536

### What was the expected outcome?

Successful deployment with domain join of FSLogix storage account to ADDS.

### Relevant log output

From the Custom Script Extension:

{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'AzureFilesDomainJoin' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.15\\Downloads\\0\\Manual-DSC-Storage-Scripts.ps1 : A \r\npositional parameter cannot be found that accepts argument 'Employees'.\r\n    + CategoryInfo          : InvalidArgument: (:) [Manual-DSC-Sto...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot. "}

**Comment by danycontre** [comment]
@SvenAelterman thanks for your feedback and submitting the PR, we are reviewing it.

**Comment by danycontre** [comment]
Addressed by @SvenAelterman on PR: https://github.com/Azure/avdaccelerator/pull/526
