### ISSUE TITLE
Bicep session host template specifies explicit disk size of 128 GB

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/avdaccelerator#523]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Deployment with a customer's custom image failed because the custom image size was 256 GB.

### Please provide the correlation id associated with your error or bug.

dcbaf73f-6566-41a6-bad5-4406062143a4

### Relevant log output

```Shell
{
    "status": "Failed",
    "error": {
        "code": "OperationNotAllowed",
        "target": "osDisk.diskSizeGB",
        "message": "The specified disk size 128 GB is smaller than the size of the corresponding disk in the VM image: 256 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size."
    }
}
```

**Comment by moisesjgomez** [comment]
@SvenAelterman thanks for reporting this bug. We are investigating the issue

**Comment by danycontre** [comment]
@SvenAelterman good catch, SH disk size should be a dynamic variable based on the image properties or a parameter.

**Comment by danycontre** [comment]
@SvenAelterman we are adding this to our backlog to work on it internally.

@swathibhat1 please help us creating a backlog item.

 @moisesjgomez
