### ISSUE TITLE
The SAS Token variable is defined but never used

### ISSUE THREAD

**Issue by randomnote1** [Azure/avdaccelerator#525]
The variable `_ArtifactsLocationSasToken ` is defined but never used. This prevents referencing the scripts in an environment where the scripts have been customized, networking is locked down, or is air gapped.

Arm version: https://github.com/Azure/avdaccelerator/blob/99fc60f1b7d978bbf712d6a8830f02cac1fa397e/workload/arm/brownfield/deployAlerts.json#L19C6-L19C32

Bicep version: https://github.com/Azure/avdaccelerator/blob/99fc60f1b7d978bbf712d6a8830f02cac1fa397e/workload/bicep/brownfield/alerts/deploy.bicep#L13C23-L13C23

**Comment by randomnote1** [comment]
# Workaround

## ARM

Append the SAS token to the end of the `.ps1` file names in [deployAlerts.json](https://github.com/Azure/avdaccelerator/blob/99fc60f1b7d978bbf712d6a8830f02cac1fa397e/workload/arm/brownfield/deployAlerts.json#L156-L157)

```json
...
    "RunbookScriptGetStorage": "Get-StorAcctInfov2.ps1?<sas token here>",
    "RunbookScriptGetHostPool": "Get-HostPoolInfo.ps1?<sas token here>",
...
```

## Bicep

Append the SAS token to the end of the `.ps` file names in [deploy.bicep](https://github.com/Azure/avdaccelerator/blob/99fc60f1b7d978bbf712d6a8830f02cac1fa397e/workload/bicep/brownfield/alerts/deploy.bicep#L79-L80)

```bicep
...
var RunbookScriptGetStorage = 'Get-StorAcctInfov2.ps1?<sas token here>'
var RunbookScriptGetHostPool = 'Get-HostPoolInfo.ps1?<sas token here>'
...
```

**Comment by danycontre** [comment]
@randomnote1 thank you for submitting the issue, we are reviewing.

cc: @JCoreMS

**Comment by JCoreMS** [comment]
This is definitely a need for air gapped clouds and on my list of things to address as soon as I can.  ;)

**Comment by JCoreMS** [comment]
This was completed in 2.1.4 per request!  Updated the UI or Deployment Button as well to reflect this change and allow for this as an option.
