### ISSUE TITLE
Sessionhostconfig - 

### ISSUE THREAD

**Issue by jonathan-vella** [Azure/avdaccelerator#536]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I am only using Entra ID, no FS Logix.
SHConfig always results in: Missing an argument for parameter 'IdentityDomainName'

### Please provide the correlation id associated with your error or bug.

fa9ff4fd-faa0-455b-8120-ddda02b10224

### Relevant log output

```Shell
VM has reported a failure when processing extension 'SessionHostConfig' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: "Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.15\Downloads\0\Set-SessionHostConfiguration.ps1 : 
**Missing an argument for parameter 'IdentityDomainName'**. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo     ...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)". More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.  (Code: VMExtensionProvisioningError)
```

**Comment by danycontre** [comment]
@jonathan-vella thanks for your feedback.

Code logic was updated to fix the bug, please try again and let us know if you have any comments.

PR: https://github.com/Azure/avdaccelerator/pull/537

cc: @swathibhat1 @moisesjgomez

**Comment by jonathan-vella** [comment]
Thanks, looks like it's sorted!
