### ISSUE TITLE
[BICEP] - deployCustomPolicyMonitoring - InvalidCreateRemediationRequest

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [Azure/avdaccelerator#539]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When avdDeployMonitoring and deployCustomPolicyMonitoring = true, deployment fails with the following error

### Please provide the correlation id associated with your error or bug.

194ecb07-59d8-44ab-89a0-1f7914565ff4

### What was the expected outcome?

Azure policy should have been created

### Relevant log output

```Shell
"details": [
                    {
                      "code": "InvalidCreateRemediationRequest",
                      "message": "The request to create remediation 'policy-set-avd-diagnostics-1' is invalid. The policy assignment '/subscriptions/###########/resourceGroups/MYRGNAME/providers/Microsoft.Authorization/policyAssignments/policy-set-deploy-avd-diagnostics-to-log-analytics' assigns a policy set definition. Remediations must specify a single policy definition reference ID within the policy set definition."
                    }
```

**Comment by danycontre** [comment]
@OrionWithrow-OHIT thanks for reporting the issue, we are reviewing it.

**Comment by danycontre** [comment]
@yshafner

**Comment by yshafner** [comment]
@danycontre @OrionWithrow-OHIT
I ran the LZA with monitoring and the monitoring policies and had no issues. 
<img width="1177" alt="Screenshot 2024-01-08 163505" src="https://github.com/Azure/avdaccelerator/assets/64444337/4c85ec06-9612-46e9-9e0b-b52d02adba5c">
<img width="1150" alt="Screenshot 2024-01-08 163206" src="https://github.com/Azure/avdaccelerator/assets/64444337/182b1bb0-5381-4729-a16a-33b1f9d82f9e">

**Comment by danycontre** [comment]
Unable to reproduce the issue or get comments from requestor.

**Comment by whysoloveless** [comment]
Hi, I'm seeing the same error. Any ideas?

**Comment by vermin1** [comment]
So am I. Was there a fix for this?
