### ISSUE TITLE
AIB- Support for 22H3

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [Azure/avdaccelerator#544]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Will you be adding support for 22H3 images?

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Would like to test with 22H3

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@OrionWithrow-OHIT thanks for your feedback we are checking.

**Comment by danycontre** [comment]
@OrionWithrow-OHIT please clarify if you are referring to 23H2 instead of 22H3.

Updates were pushed to add Win 11 23H2 as an option for custom image build and baseline deployments.

cc: @swathibhat1 @moisesjgomez

**Comment by OrionWithrow-OHIT** [comment]
Confirmed this update is working. I had not gotten the push due to a Git issue.


Orion Withrow (He/Him/His)



TRULY HUMAN NOTICE: Getting this email out of normal working hours? We work at a digitally-enabled relentless pace, which can disrupt our ability to sleep enough, eat right, exercise, and spend time with the people that matter most. I am sending you this email at a time that works for me. I only expect you to respond to it when convenient to


________________________________

**Comment by danycontre** [comment]
Thanks for the updates.
