### ISSUE TITLE
[Portal UI] - VM Size selector showing availability for region selected in sessionHostsRegion

### ISSUE THREAD

**Issue by sindkor** [Azure/avdaccelerator#554]
### What happened? Provide a clear and concise description of the bug, including deployment details.

During the UI-deployment, two regions are selected. One in the `resourceScope`-step, and one in the `sessionHostsRegion`-step. The latter is where the session hosts are deployed to. However, the VM Size selector lists VM sizes available in the region set in the `resourceScope`.

If I, for example, want to have my management-resources (host pool, application group, etc.) in West Europe, but I want to deploy a host in the `HBv4`-series I can do that to East US. The sizes of that family, is however, not listed in the size selector. Instead, only VMs available in West Europe are listed.

### What was the expected outcome?

VM Sizes available in the region selected in the `sessionHostsRegion` are shown in the size selector.

**Comment by moisesjgomez** [comment]
@sindkor @danycontre This issue has been fixed with the latest update. We have added a "scope" value to the size selector pointing at the session host region. Please run again and let us know if you face the same issue.
