### ISSUE TITLE
Add deployGPUPolicies to UI

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#561]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

When deploying AVD Accelerator from the UI, there is no option to set deployGPUPolicies to 'false'. This is my experience in the Azure Gov UI. Have not tested in Azure Commercial.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

When someone doesn't have the permissions to apply azure policy to their subscription, they can disable this

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

I click "Edit Template" and I can change it to false. Good workaround, but not ideal

**Comment by danycontre** [comment]
@chbragg thanks for the feedback working on adding the feature to the UI.

cc: @swathibhat1

**Comment by danycontre** [comment]
Fixed with PR 565
