### ISSUE TITLE
App Attach VM: Add Custom Script Extension Option

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#566]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

I think it will provide some more flexibility with the App Attach VM if it's possible a CSE option like see you with the native Azure UI deployments is an option.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

App Attach is growing and becoming more of an option for customers to try out, especially with Entra Joined VM's now.  The service has a ton of new features and more coming in the future, so having a VM that can be quickly stood up to build apps with some flexibility for each customer to use would provide a lot more possibilities.

### Can you describe any alternatives that you have taken since this feature does not exist?

Create a custom build with custom scipt extensions.

**Comment by danycontre** [comment]
@swathibhat1 let's create an item on the backlog to work this feature.

@brmcmill  we will work on the feature.

cc: @JCoreMS
