### ISSUE TITLE
[Azure Disk Encryption] - Add support for Azure Disk Encryption

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#568]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Add support so Azure Disk Encryption can be used instead of Encryption At Host for AVD VMs

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

When onboarding VM to Intune and checking compliance policies, Azure Disk Encryption satisfies the Bitlocker compliance check out of the box and Encryption At Host does not.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@chbragg thanks for reporting the issue, we are reviewing it.

**Comment by danycontre** [comment]
@swathibhat1 let's create an item on the backlog to work this feature.

@chbragg we will work on the feature.
