### ISSUE TITLE
Purpose of terraform/greenfield/AADDSscenario not documented

### ISSUE THREAD

**Issue by mloskot** [Azure/avdaccelerator#578]
### Let us know the feedback or general question

There is this very helpful table which nicely explains purpose of the different scenarios:

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/readme.md?plain=1#L43-L48

but it is lacking entry for [AADDSscenario](https://github.com/Azure/avdaccelerator/tree/2c73a3e142bc757853424e37fe03dbf4146fbd2c/workload/terraform/greenfield/AADDSscenario).

It would be helpful if the difference between ADDS and AADDS scenarios is explained.

**Comment by danycontre** [comment]
@mloskot thanks for your feedback, this was just addressed with PR 584.

**Comment by mloskot** [comment]
Looks good, thank you @danycontre
