### ISSUE TITLE
azurerm_user_assigned_identity.mi is not used for FSLogix in AADDSscenario and ADDSscenario

### ISSUE THREAD

**Issue by mloskot** [Azure/avdaccelerator#579]
### Let us know the feedback or general question

This seems like a copy paste left over, a bit confusing though. that is not referenced anywhere:

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADDSscenario/afstorage.tf#L1-L5

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/ADDSscenario/afstorage.tf#L1-L5

Only the zerotrust scenario seems to reference `azurerm_user_assigned_identity.mi`.

**Comment by danycontre** [comment]
@swathibhat1
