### ISSUE TITLE
AADDSscenario says Entra ID joined but joins domain controller

### ISSUE THREAD

**Issue by mloskot** [Azure/avdaccelerator#580]
### Let us know the feedback or general question

The [AADDSscenario/readme.md](https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADDSscenario/readme.md?plain=1#L5) says:

> This scenario deploys a new Azure Virtual Desktop workload with Microsoft **Entra ID joined** session host

while in the code it makes use of the `JsonADDomainExtensions`  for a regular domain join:

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADDSscenario/host.tf#L65-L82

If this scenario was creating Entra ID joined VM-s, should shouldn't it rather setup the VM extension `AADLoginForWindows` , as after https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows:

> The `AADLoginForWindows` extension must be installed successfully for the VM to complete the **Microsoft Entra join** process.

and

> After you enable this capability, **your Windows VMs in Azure will be Microsoft Entra joined**. You cannot join them to another domain, like on-premises Active Directory or Microsoft Entra Domain Services.

I believe there exists the confusion caused by describing "Entra ID join" while performing a domain join.

**Comment by danycontre** [comment]
@mloskot thanks for your feedback, readme was updated to accordingly, the scenario is meant to join session host to Microsoft Entra Domain Services domain controllers not to Microsoft Entra ID.

**Comment by mloskot** [comment]
@danycontre I see. Thank you!
