### ISSUE TITLE
azurerm_storage_share.FSShare created for FSLogix is unused

### ISSUE THREAD

**Issue by mloskot** [Azure/avdaccelerator#581]
### Let us know the feedback or general question

In the Terraform of the several scenarios, there is this Azure Storage Account and Azure File share created, presumably, for use as container for FSLogix profiles on AVD host VM-s:

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADDSscenario/afstorage.tf#L25-L28

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/ADDSscenario/afstorage.tf#L25-L28

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADscenario/afstorage.tf#L34-L37

https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/terraform/greenfield/AADDSscenario/afstorage.tf#L25-L28

But, that `azurerm_storage_share.FSShare` resource is not referenced anywhere further in the code:

![image](https://github.com/Azure/avdaccelerator/assets/80741/512edb0c-4858-4d3f-9804-1bea13d522bd)

How are the AVD host VM-s set up with FSLogix?
Is it part of custom image build, but not committed to the repo?

It looks like only the Bicep variant of the deployment actually performs setting up of host VM-s with FSLogix:
- https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/bicep/modules/avdSessionHosts
- https://github.com/Azure/avdaccelerator/blob/c6e13867711a44443256505d8dad50ca79a267ea/workload/scripts/Set-SessionHostConfiguration.ps1

**Comment by danycontre** [comment]
@mloskot thanks for your feedback, FSLogix setup for terraform is a work in progress under PR 570.

Current storage account references in the code are a preparation for the full FSLogix setup.
