### ISSUE TITLE
Policy remediation error during portal deployment

### ISSUE THREAD

**Issue by integyjc** [Azure/avdaccelerator#587]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Several attempts at deploying via the Portal result in the same error every time:

{"customHtml":{"htmlTemplate":"<code><div>The request to create remediation 'policy-set-avd-diagnostics-3' is invalid. The policy assignment '/subscriptions/440c2afa-db86-4439-bf11-13a06d9xxxxx/resourceGroups/rg-avd-main-prod-uks-storage/providers/Microsoft.Authorization/policyAssignments/policy-set-deploy-avd-diagnostics-to-log-analytics' assigns a policy set definition. Remediations must specify a single policy definition reference ID within the policy set definition.</div></code>","viewModel":null}}

### Please provide the correlation id associated with your error or bug.

2c18f7d9-c9a7-4938-934c-827701afbfa8

### What was the expected outcome?

Successful deployment

### Relevant log output

```Shell
Raw error:

{
  "code": "DeploymentFailed",
  "target": "/subscriptions/440c2afa-db86-4439-bf11-13a06d9xxxxx/resourceGroups/rg-avd-main-prod-uks-storage/providers/Microsoft.Resources/deployments/Remm-Diag-policy-set-avd-diagnostics-3",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "InvalidCreateRemediationRequest",
      "message": "The request to create remediation 'policy-set-avd-diagnostics-3' is invalid. The policy assignment '/subscriptions/440c2afa-db86-4439-bf11-13a06d9xxxxx/resourceGroups/rg-avd-main-prod-uks-storage/providers/Microsoft.Authorization/policyAssignments/policy-set-deploy-avd-diagnostics-to-log-analytics' assigns a policy set definition. Remediations must specify a single policy definition reference ID within the policy set definition."
    }
  ]
}
```

**Comment by danycontre** [comment]
@integyjc thanks for the feedback.

@yshafner

**Comment by integyjc** [comment]
Thanks @danycontre - I think this one can be closed as environment related. Despite the error being a bit vague, it does seem that policies left from previous failed deployments were the cause. These policy definitions and assignments remained at the subscription level even if the resource groups the policies are assigned to are deleted following a failed deployment. Manually deleting the policy assignments and definitions from the subscription level and waiting an hour resulted in a clean deployment.

**Comment by PotterOtukile54** [comment]
@integyjc I just came across the same problem and looking for a resolve

![grab](https://github.com/Azure/avdaccelerator/assets/52814462/a3f0fbac-eb68-4d8d-8e51-6adad7590a9e)

**Comment by integyjc** [comment]
Hi @PotterOtukile54 that looks like a different error to the one i've reported on here
