### ISSUE TITLE
AS-Disable-Microsoft-Entra-ID-User-From-Entity  Sentinel PlaybookTemplate BUG

### ISSUE THREAD

**Issue by PotterOtukile54** [Azure/avdaccelerator#589]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Several attempts at deploying via the Portal result in the same error every time:

ERROR TYPE {"customHtml":{"htmlTemplate":"<code><div>The template validation failed: 'The 'runAfter' property of template action 'HTTP_-_Authenticate' at line '1' and column '810' contains non-existent action: 'Initialize_variable_-_Affected_Azure_AD_Users'.'.</div></code>","viewModel":null}}

![image](https://github.com/Azure/avdaccelerator/assets/52814462/9f683af9-b8f5-4094-983e-3fd792e20b67)

### Please provide the correlation id associated with your error or bug.

95ae5d49-060c-445a-b1cf-9f1af2063f50

### What was the expected outcome?

Succesful Deployment

### Relevant log output

```Shell
ERROR TYPE {"customHtml":{"htmlTemplate":"<code><div>The template validation failed: 'The 'runAfter' property of template action 'HTTP_-_Authenticate' at line '1' and column '810' contains non-existent action: 'Initialize_variable_-_Affected_Azure_AD_Users'.'.</div></code>","viewModel":null}}



Raw Log
{
  "code": "DeploymentFailed",
  "target": "/subscriptions/XXXXXX/resourceGroups/XXXXXXXXXX/providers/Microsoft.Resources/deployments/Microsoft.Template-20240222004911",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "InvalidTemplate",
      "message": "The template validation failed: 'The 'runAfter' property of template action 'HTTP_-_Authenticate' at line '1' and column '810' contains non-existent action: 'Initialize_variable_-_Affected_Azure_AD_Users'.'."
    }
  ]
}
```

**Comment by danycontre** [comment]
@PotterOtukile54 please provide the details of your deployment, you can get this info from the deployments at the subscription level.
