### ISSUE TITLE
storageAzureFiles bicep module handling DirectoryServiceOptions incorrectly

### ISSUE THREAD

**Issue by pazdedav** [Azure/avdaccelerator#590]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying the Baseline workload with Bicep and using **FSLogix with Entra ID Domain Services** configuration, the `Storage-fslogix-XXXX` nested deployment fails with the following error:

```
The value 'EntraDS' is not allowed for property DirectoryServiceOptions.
```

### Please provide the correlation id associated with your error or bug.

e9e82a70-912c-4f97-a352-f89c022f2ba4

### What was the expected outcome?

Successful deployment of an Azure Storage account, configured with Entra ID Domain Services integration.

### Relevant log output

```Shell
{
  "code": "DeploymentFailed",
  "target": "/subscriptions/xxx/resourceGroups/rg-avd-vdi2-test-euw-storage/providers/Microsoft.Resources/deployments/Storage-fslogix-20240228T084427Z",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "InvalidRequestPropertyValue",
      "message": "The value 'EntraDS' is not allowed for property DirectoryServiceOptions."
    }
  ]
}
```

**Comment by danycontre** [comment]
@pazdedav thanks for reporting the issue and submitting a PR with the fix, it has been merged.
