### ISSUE TITLE
[PLACEHOLDER] - Place a descriptive title here

### ISSUE THREAD

**Issue by sandrocp13** [Azure/avdaccelerator#593]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I'm trying to deploy a new host session to an existent host pool. but when I click try to use Deploy to Azure button, I'm receiving this error when the portal opens.
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/avdaccelerator/new-sh/workload/arm/brownfield/deployNewSessionHostsToHostPools.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 
There was an error downloading from URI 'https://raw.githubusercontent.com/Azure/avdaccelerator/new-sh/workload/portal-ui/brownfield/portalUiNewSessionHosts.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

The deployment opens to allow me to initiate the deploy new host.

**Comment by danycontre** [comment]
@sandrocp13 thanks for reporting the bug, we just pushed an update to fix the deploy button.

Please try again.
