### ISSUE TITLE
Route to Identity vNet not created in Route Table

### ISSUE THREAD

**Issue by davde-ms** [Azure/avdaccelerator#601]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When using the solution from the Azure Portal, a Route Table gets created for AVDServiceTraffic and AVDStunTurnTraffic.
However there is no route created for the Identity vNet which leads to a failure for the domain join process.

This has been reported by a customer of mine so I don't have any correlation ID to provide although I've seen the deployment failure. Customer was able to workaround the issue by monitoring the creation of the Route Table and quickly add a route to it (manually) during the deployment process.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Route entry for the identity vNet is automatically added to the Route Table when using the Portal based deployment.

**Comment by danycontre** [comment]
@davde-ms thanks for submitting the feedback, we are reviewing it.

**Comment by danycontre** [comment]
Fix under testing on the feature branch: issue-601

**Comment by danycontre** [comment]
@davde-ms please let us know if you have any updates on testing.
