### ISSUE TITLE
Italy North as Session Host and management VM region

### ISSUE THREAD

**Issue by gclementimicrosoft** [Azure/avdaccelerator#604]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I choose to deploy a new Session Host in west europe but since compute capacity is not availabile in west europe I must deploy virtual network and compute session hosts and management VMs in Italy North

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Relevant log output

```Shell
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'varSessionHostLocationAcronym' is not valid: The language expression property 'italynorth' doesn't exist, available properties are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, brazilsoutheast, canadacentral, canadaeast, centralindia, centralus, chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, eastasia, eastus, eastus2, francecentral, francesouth, germanynorth, germanywestcentral, japaneast, japanwest, jioindiacentral, jioindiawest, koreacentral, koreasouth, northcentralus, northeurope, norwayeast, norwaywest, southafricanorth, southafricawest, southcentralus, southeastasia, southindia, swedencentral, switzerlandnorth, switzerlandwest, uaecentral, uaenorth, uksouth, ukwest, usdodcentral, usdodeast, usgovarizona, usgovtexas, usgovvirginia, westcentralus, westeurope, westindia, westus, westus2, westus3'.. Please see https://aka.ms/arm-functions for usage details.'."}
```

**Comment by danycontre** [comment]
@gclementimicrosoft thanks for submitting the issue.

We pushed a fix in a feature branch (issue-604), please test the deployment again using this link:

https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Favdaccelerator%2Fissue-604%2Fworkload%2Farm%2Fdeploy-baseline.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Favdaccelerator%2Fissue-604%2Fworkload%2Fportal-ui%2Fportal-ui-baseline.json

Please keep us updated on the test outcome.

**Comment by danycontre** [comment]
@gclementimicrosoft  please let us know if you have any updates on testing.

**Comment by danycontre** [comment]
Branch merged.
