### ISSUE TITLE
Spelling Incorrect for Resource Tagging - Validation Fails

### ISSUE THREAD

**Issue by JCoreMS** [Azure/avdaccelerator#608]
### What happened? Provide a clear and concise description of the bug, including deployment details.

In the tab for the overall deployment solution there is a spelling mistake in the custom UI definition within the "Resource tagging" section. Specifically for the drop down for "Mission Critical" which is spelled "Missin-Crtical" and valid per the ARM template thus validation fails.  This drop down entry needs to be updated to "Mission-Critical".  (Missing the 'o') 

### Please provide the correlation id associated with your error or bug.

N/A - Fails validation when selecting to Tag resources and the entry for "Workload criticality" 

### What was the expected outcome?

Deployment with the pre-configured drop downs for the tagging.

### Relevant log output

```Shell
Need to edit the Custom UI definition...
- Resource Tagging Section
- Item "Workload criticality"
- Edit drop down option item Missin-Critical (Change to Mission-Critical)
Verify ARM (JSON) template and BICEP have the correct spelling for the parameter regarding valid inputs
```

**Comment by danycontre** [comment]
@JCoreMS thanks for reporting the issues, we just pushed the fix.

Please try again.
