### ISSUE TITLE
[Features] - Enroll the VM in Intune

### ISSUE THREAD

**Issue by boujrafh** [Azure/avdaccelerator#613]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Hello,

I appreciate you code. thank you for that.

When you create in the portal Azure a VM to the Host Pool,  It's possible to enroll the VM in Intune.

Could you add feature in you code please ?

Best Regards

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

If the VM is enroll in Intune, you can push the policies, Push Update Microsoft, etc.

### Please provide the correlation id associated with your error or bug.

there are not error, it's feature

**Comment by danycontre** [comment]
@swathibhat1

**Comment by danycontre** [comment]
@boujrafh thanks for your feedback.

The option to enroll into intune is available in the portal UI:
![image](https://github.com/Azure/avdaccelerator/assets/78437433/40f081b1-f473-487b-989b-2ad4190d3634)

And in the Bicep code:
https://github.com/Azure/avdaccelerator/tree/main/workload/bicep/deploy-baseline.bicep
    @sys.description('Required, Enroll session hosts on Intune. (Default: false)')
    param createIntuneEnrollment bool = false
