### ISSUE TITLE
Feature Request  - Add Zero-Trust support for Brownfield Add Session Host

### ISSUE THREAD

**Issue by jcoyne-msft** [Azure/avdaccelerator#614]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Our AVD LZA baseline supports the use of Encryption at Host for Zero-Trust. This option is not available in the Portal (have not tested other deployment options).

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Customers using our AVD LZA repo targeting Zero-Trust will definitely use this feature when expanding their existing host pools. Missing this feature makes the brownfield scenario to deploy VMs with Zero-trust not possible.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

Post deployment configuration of the VMs. Time consuming and not scalable. Defeats the purpose of the LZA if our customers have to create their own templates for adding VMs to an existing host pool.

**Comment by danycontre** [comment]
@swathibhat1

**Comment by danycontre** [comment]
@swathibhat1 let's add this one on our backlog and track it on ADO.
