### ISSUE TITLE
[Bug] AVD Monitoring - failed deployments when avdDeployMonitoring is set to false

### ISSUE THREAD

**Issue by pazdedav** [Azure/avdaccelerator#620]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying the AVD baseline using the bicep 'flavour', we are setting the following values for 'Baseline AVD module':
- `avdDeployMonitoring: false`
- `deployAlaWorkspace: false`
- `deployCustomPolicyMonitoring: false`
- we don't provide a value for `alaExistingWorkspaceResourceId`

We don't want the accelerator to configure the environment for monitoring because we have a set of robust Azure policies that centrally takes care of both AMA extensions for session hosts and diag. settings for other resources. We don't want to provision a separate LA workspace and we dont' want to reference an existing one.

The deployment fails on 'SH-Batch-xxx' sub-deployment (session hosts) due to `TemplateViolation` error (see below).

Based on our troubleshooting, it seems the issue is in `workload/bicep/modules/avdSessionHosts/deploy.bicep`, lines 292-295, where a resourceId is parsed but since it's getting an empty string, that expression fails, but there could be other reasons.

### Please provide the correlation id associated with your error or bug.

57b81c7c-9c63-4e8b-a9f1-62bd30b4a0da

### What was the expected outcome?

We want to be able to skip a deployment of monitoring components completely. We have a robust policy engine that centrally takes care of both AMA extensions for session hosts and diag. settings for other resources.

### Relevant log output

```Shell
{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The template resource '' at line '1' and column '12588' is not valid: The language expression property array index '2' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'.",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 1,
        "linePosition": 12588,
        "path": "properties.template.resources.alaWorkspace"
      }
    }
  ]
}
```

**Comment by danycontre** [comment]
Thanks @pazdedav for the feedback, we are checking.

**Comment by danycontre** [comment]
@pazdedav we continue to troubleshoot, in the meantime, please go inside the failed deployment SH-Batch* and provide details on which internal deployment failed.

**Comment by pazdedav** [comment]
This is what I see on the 'AVD Baseline' deployment level:
![image](https://github.com/Azure/avdaccelerator/assets/12873988/f30a6ec6-a456-43de-8cd2-f8fd25b9e3ed)

However, when I try to open the SH-Batch deployment, it doesn't show nested deployments, only this:
![image](https://github.com/Azure/avdaccelerator/assets/12873988/b537638c-991d-4117-8328-264cc6801ba1)

**Comment by danycontre** [comment]
@pazdedav thanks for the info, we have been trying to replicate the issue but no luck so far.

Please share the parameters you are using for the deployment (please redact the credentials related ones).
