### ISSUE TITLE
BROKEN - Session Host Config Host Pool Registration Token

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#624]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I believe there was a recent software update to Azure that broke the Host Pool Registration Token call. The error message shown during the session host configuration is: 
SH-Config-0-2-20240625T135515Z' at line '1' and column '186428'. 'The language expression property 'token' can't be evaluated.'  (Code: InvalidTemplate).

This might be related to this:
https://github.com/Azure/bicep-types-az/issues/2023

Inside the github issue, there are other potential options for calling the token

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

The session host would be joined to the Host Pool  using the registration token

**Comment by cvondeylen** [comment]
We are also experiencing this issue. Was working fine yesterday using the bicep code `reference(hostPoolId, '2021-01-14-preview').registrationInfo.token`

**Comment by danycontre** [comment]
Thanks for reporting the issue, we are working on it.

@moisesjgomez @swathibhat1

**Comment by danycontre** [comment]
Deployment is working again.

Current API in use is being updated, so the current code will not work, therefore we are updating the code to fetch the registration token in a different way.

**Comment by danycontre** [comment]
Fixed with PR #623
