### ISSUE TITLE
[Feature] - Support for Multiple Hostpools and Access Group Assignments

### ISSUE THREAD

**Issue by bhlillevik** [Azure/avdaccelerator#625]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

This feature enhancement aims to enable the assignment of multiple application group types across different host pools. The deployment scenario involves a more flexible configuration, where users can be assigned to both Desktop and RemoteApp groups but in separate host pools.

Additionally, the feature should support adding multiple groups for access assignment across these different host pools. This will facilitate efficient management of user access and improve resource allocation when deploying multiple host pools with the accelerator.

During the deployment process, administrators will have the option to configure a list of application group assignments and host pool memberships in a more granular and customizable manner, based on the organization and users needs.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

After the recent update regarding the preferred application group type, where a user should only be assigned one app group type within the same hostpool, it would be highly beneficial to have the option to deploy multiple hostpools. This would enable assigning a user to both Desktop and RemoteApp groups, ensuring greater flexibility and utility.

MS Docs Reference: [Preferred Application Group Type](https://learn.microsoft.com/en-us/azure/virtual-desktop/preferred-application-group-type)

Additionally, it would be an huge advantage to support the assignment of multiple groups when adding multiple hostpools. Currently, as per my knowledge, this functionality is not available:

![image](https://github.com/Azure/avdaccelerator/assets/90832108/e8eae682-9141-4915-99a3-d00e4ad6aabf)

Furthermore, the UI does not support this feature:

![image](https://github.com/Azure/avdaccelerator/assets/90832108/85e1af2a-156a-4654-adfb-803f78547f66)

Implementing these enhancements would significantly improve the flexibility and usability of Azure Virtual Desktop deployments.

Thank you for considering this feature request.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

Manually add a new hostpool after deployment and add more groups to access the different app groups.

**Comment by danycontre** [comment]
@bhlillevik thank you for the great feedback, we are investigating it and adding into our backlog.

@swathibhat1 please let's create this item for tracking.
