### ISSUE TITLE
[Win21H2 EOL] - Update Windows 11 Image References to more recent versions

### ISSUE THREAD

**Issue by cocallaw** [Azure/avdaccelerator#628]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Update the image referenced used by the AVD LZA to be current versions as some of the versions listed for Windows 11 are approaching EOL.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

The current templates and documentation references image versions that are older and approaching EOL which could result in security and stability issues if the customer does not update 

On October 8, 2024 Windows 11 Enterprise will be EOL - 
https://learn.microsoft.com/en-us/lifecycle/products/windows-11-enterprise-and-education?branch=live

**Comment by danycontre** [comment]
@cocallaw thanks for the feedback, we are reviewing the issue.

**Comment by danycontre** [comment]
Image SKUs updated to remove 21H2
