### ISSUE TITLE
Sporadic Azure VM Extension Deployment Failures for Entra ID and Intune Join in Large-Scale Terraform Deployments

### ISSUE THREAD

**Issue by florian-de** [Azure/avdaccelerator#634]
### What happened? Provide a clear and concise description of the bug, including deployment details.

**Issue Description:**

We are encountering sporadic issues during large-scale deployments of Azure Virtual Machines (AVD hosts) using Terraform. Our setup involves the deployment of up to 100 AVD hosts in parallel, with extensions for Entra ID, Intune, and Host Pool join being applied as part of the provisioning process.

**Problem:**

In deployments of 100 AVD hosts, we configure Terraform to deploy resources with a -parallelism setting of 100. The deployment proceeds smoothly most of the time; however, on some occasions, we encounter errors specifically related to the Entra ID and Intune Join extensions. These errors occur on 2-3 hosts per deployment run.

**Additional Details:**

We are using the identical logic as in the AVD Accelerator, where a custom script extension is employed to execute the Desired State Configuration (DSC) for AVD. This logic is applied consistently within our Terraform scripts.

**Further Information:**

- The extension appears to be deployed successfully, but the Terraform apply ultimately reports an error.
- The join seems to be completed, but the VM does not enter the SecureVM state as expected, resulting in a failure of the MDM enrollment.
- Our current workaround involves manually uninstalling the extension on the affected VMs and then re-running the Terraform deployment, which is not ideal for our large-scale operations.

**Reproduction:**

1. Deploy 100 AVD hosts using Terraform with a -parallelism setting of 100.
2. Include extensions for Entra ID, Intune, and Host Pool join in the deployment.
3. Observe that 2-3 VMs report the aforementioned error while the rest deploy successfully.

**Actual Behavior:**

2-3 VMs report failures related to the Entra ID and Intune Join extensions, causing the overall Terraform deployment to report errors even though the extension seems to be partially applied.

**Steps to Mitigate:**

As a temporary solution, we uninstall the extensions manually on the affected VMs and re-run the Terraform deployment. However, this is not a sustainable solution for large-scale operations.

**Request for Help:**

We would appreciate any guidance or suggestions on how to address this issue, particularly in terms of ensuring all extensions are applied successfully across all VMs in a single Terraform deployment run.

**Environment:**

Terraform version: ~>1.7.0
Azure Provider version: 3.89
Logic: Identical to AVD Accelerator using custom script extension to execute DSC for AVD

### What was the expected outcome?

All VMs should successfully complete the Entra ID and Intune Join processes without errors, and Terraform should complete without reporting failures.

### Relevant log output

```Shell
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'xxxb-01-52-aadJoin' (publisher 'Microsoft.Azure.ActiveDirectory' and type 'AADLoginForWindows'). Error message: 'AAD Join failed with status code: -2145648524. AzureSecureVMJoinOperation: AzureSecureVM Join failed. VM already joined but not in SecureVM state, MDM enrollment to be performed. This is not supported. Join the device and retry the command.'. More information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot."
```

**Comment by danycontre** [comment]
@florian-de thanks for your feedback.

@swathibhat1 for visibility and assigning to TF team.

**Comment by danycontre** [comment]
@florian-de sounds like you may be hitting limits on the subscription or tenant, to further troubleshoot please open a support request and ask the support engineer to add my account to the thread (Dany Contreras).

Closing this issue as we are taking it through Microsoft Support.
