### ISSUE TITLE
[PLACEHOLDER] - KMS lPs missing

### ISSUE THREAD

**Issue by jcoyne-msft** [Azure/avdaccelerator#637]
### What happened? Provide a clear and concise description of the bug, including deployment details.

The KMS server IPs are using only the secondary IP listed in our docs.

"name": "WindowsActivationKMS",
                        "properties": {
                          "priority": 140,
                          "access": "Allow",
                          "description": "Session host traffic to Windows license activation services",
                          "destinationAddressPrefix": "23.102.135.246",
                          "direction": "Outbound",
                          "sourcePortRange": "*",
                          "destinationPortRange": "1688",
                          "protocol": "Tcp",
                          "sourceAddressPrefix": "VirtualNetwork"

The first DNS name of the KMS server for the Azure Global cloud is azkms.core.windows.net with two IP addresses: 20.118.99.224 and 40.83.235.53. The second DNS name of the KMS server for the Azure Global cloud is kms.core.windows.net with an IP address of 23.102.135.246.

See here:
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows/custom-routes-enable-kms-activation#solution

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

IPs should be reflected of latest IP addresses provided in our docs.

**Comment by danycontre** [comment]
@jcoyne-msft thank you for your feedback we are reviewing it.
