### ISSUE TITLE
collection of windows eventlogs from session hosts not working

### ISSUE THREAD

**Issue by d875167** [Azure/avdaccelerator#638]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When doing a bicep deployment with following parameters:

"avdIdentityServiceProvider": ADDS
"avdDeployMonitoring": true
"deployAlaWorkspace": true
"deployCustomPolicyMonitoring": false

Log Analytics workspace and data collection rules are correctly deployed, session host is registered as a resource in the data collection rule but the windows eventlogs don't get send to the workspace.

I assume because managed identity is not enabled for the session hosts when using ADDS as IdentityServiceProvider.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Table "Event" visible in  log analyticts workspace

**Comment by danycontre** [comment]
@d875167 thank you for submitting the issue, we are reviewing it.

**Comment by danycontre** [comment]
@d875167 bug fixed by PR 641, please try again.

@swathibhat1 @moisesjgomez
