### ISSUE TITLE
Getting Started - Baseline Deployment Guide deployment failure

### ISSUE THREAD

**Issue by sandrocp13** [Azure/avdaccelerator#643]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I'm trying to deploy my new environment in a new tenant, but when I access the link inside https://github.com/Azure/avdaccelerator/blob/main/workload/docs/getting-started-baseline.md, the link is not opening the Custom deployment template. It just opens the Azure Portal.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Start de custom template deployment

**Comment by danycontre** [comment]
@sandrocp13 thanks for your feedback, the bug was fixed, please try again.

@swathibhat1
