### ISSUE TITLE
Getting Started - Baseline Deployment Guide error

### ISSUE THREAD

**Issue by sandrocp13** [Azure/avdaccelerator#644]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I'm getting error message about SKU not available, but the listed SKU is not the one I'm using on my deployment. I'm using DC2s_v3. As you can see, the failure indicates I'm using B2ms, that I'm not!
        {
          "code": "SkuNotAvailable",
          "message": "The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_B2ms' is currently not available in location 'southcentralus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details."

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Deploy new environment.

**Comment by danycontre** [comment]
@sandrocp13 B2ms was the default SKU used for management VM deployment, the template was updated to use the same one provided for session hosts.

Please remember to remove the management VM was the deployment is completed.

@moisesjgomez @swathibhat1
