### ISSUE TITLE
Joining storage account to ADDS stuck at gpupdate

### ISSUE THREAD

**Issue by bgrbab** [Azure/avdaccelerator#648]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Script-DomainJoinStorage.ps1 is stuck at "gpupdate /force" when there's gpo(s) requiring a restart. It's working with "gpupdate /force /wait:0".

**Comment by danycontre** [comment]
@bgrbab thank you for your feedback, we are reviewing it.

**Comment by AndreasSMoe** [comment]
Any progress on this issue?

**Comment by danycontre** [comment]
@AndreasSMoe we just pushed a testing branch (https://github.com/Azure/avdaccelerator/tree/issue-648) with the updates, please test deployments from it and let us know the outcome.
