### ISSUE TITLE
Brownfield deployment new session host is deployed with MMA extension

### ISSUE THREAD

**Issue by d875167** [Azure/avdaccelerator#650]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When using bicep brownfied option to deploy an extra sessions host it is still deployed with the Microsoft Monitoring Agent instead of the new  AzureMonitorWindowsAgent.
Also managed identity is not enabled for the session host when using ADDS as identityServiceProvider.

Is it possible to update this?

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@d875167 thanks for your feedback, we just updated the code to fix the bugs (PR 654).

Please try again.
