### ISSUE TITLE
Please update TF code and remove unneeded explicit dependencies.

### ISSUE THREAD

**Issue by mrshiva** [Azure/avdaccelerator#651]
I found a lot of explicit dependencies in the TF code which are not needed, because the resource/module has the direct reference to the resource, which you are setting up as 'depends_on'.

Here is the detailed description for this: 

https://dev.to/pwd9000/terraform-understanding-implicit-and-explicit-dependencies-n9l

**Comment by jensheerin** [comment]
@mrshiva, thank you for raising the issue please see comments on https://github.com/Azure/avdaccelerator/issues/652
Thank you!

**Comment by mrshiva** [comment]
Thanks for sharing, will check those!
