### ISSUE TITLE
TF code doesn't follow guidelines for modular design

### ISSUE THREAD

**Issue by mrshiva** [Azure/avdaccelerator#652]
TF code for landing zone doesn't follow many guidelines for modular design.

For example:
- Module's files are not structured well;
- Modules have inconsistent file name (outputs vs output);
- Missing 'outputs' from many modules;
- etc.

**Comment by jensheerin** [comment]
@mrshiva, thank you for logging the issue. The code is being refactor to use the AVM modular design and you can find the ones related to AVD here:
https://registry.terraform.io/modules/Azure/avm-ptn-avd-lza-managementplane/azurerm/latest
https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-hostpool/azurerm/latest
https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-applicationgroup/azurerm/latest
https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-workspace/azurerm/latest
https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-scalingplan
https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights
For a complete list of the TF modules look here https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/
Thank you again for raising the issue.

**Comment by mrshiva** [comment]
Thanks for sharing, will check those!
