### ISSUE TITLE
Question - Conditional deployment on existing Key Vault in module:avdSessionHosts/deploy.bicep

### ISSUE THREAD

**Issue by bhlillevik** [Azure/avdaccelerator#655]
### General question

In this module: **bicep/modules/avdSessionHosts/deploy.bicep** we are calling on existing keyvault if not using EntraID:

![image](https://github.com/user-attachments/assets/afe7dc0b-1074-4db9-8790-b139109b0390)

I’m trying to understand why this conditional check is being used. Regardless of whether Entra ID is used or not, we still need to retrieve the *vmLocalUserPassword* and *hostPoolRegistrationToken* secrets from the Key Vault during the deployment of session hosts.

In my understanding, if a conditional check is applied to an existing resource and the condition isn’t met, the deployment should return null for that resource. However, in this case, it seems that even when the condition isn’t met, the deployment still retrieves these secrets from the Key Vault and uses them as inputs for the *vmLocalUserPassword* and *hostPoolRegistrationToken* parameters.

How is this possible? Is there something about the conditional logic or the way Bicep handles existing resources that might cause this behavior, or is there another mechanism I have overlooked?

**Comment by danycontre** [comment]
@bhlillevik  thank you for your feedback, we are reviewing it.

@swathibhat1 @moisesjgomez

**Comment by danycontre** [comment]
@bhlillevik you are right the keyvault call is needed regardless of the identityServiceProvider in use, this was a bug in the code, but we are also escalating the bug to Bicep since the condition wasn't been checked for the item execution.

Please check the new code and let us know if you have any comments/feedback.

@swathibhat1
