### ISSUE TITLE
[ADJoin & MFA] - Synchronizing AAD users fails because of MFA requirement for ADJoin account

### ISSUE THREAD

**Issue by tcorveleyn** [Azure/avdaccelerator#656]
### What happened? Provide a clear and concise description of the bug, including deployment details.

I managed to deploy the AAD VM as per the AVD Accelerator instructions. However, when configuring the AAD server and trying to set up AAD Connect, I run into an issue because the account used for the domain join ('adjoin') is forced to have MFA. So I'm looking for a way to disable or avoid this. I can see the AAD Sync account being created in my tenant/subscription, but the regular users like Bob Jones or Bill Smith do not. Not sure the creation process of the AAD Sync account was correctly completed, as per the log output I share further below.

### Please provide the correlation id associated with your error or bug.

107569eb-5cce-4a49-97dd-9a033a7d4c83

### What was the expected outcome?

AAD users being synchronized to my Azure tenant.

### Relevant log output

```Shell
[ERROR] GetServiceAccount: the retry time limit for service account authorization has been exceeded.
Exception Data (Raw): Microsoft.Azure.ActiveDirectory.Synchronization.ProvisioningWebServiceAdapter.AzureADServiceAccountException: Unable to create the synchronization service account for Azure Active Directory.  Retrying this operation may help resolve the issue.   ---> Microsoft.Identity.Client.MsalUiRequiredException: AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access '00000002-0000-0000-c000-000000000000'. Trace ID: 5e7911a8-0b49-4886-aadf-70492a695900 Correlation ID: 107569eb-5cce-4a49-97dd-9a033a7d4c83 Timestamp: 2024-08-28 14:29:35Z
```

**Comment by danycontre** [comment]
@tcorveleyn thank you for your feedback, we are reviewing it.

**Comment by danycontre** [comment]
@tcorveleyn please confirm which deployment are you executing.

**Comment by danycontre** [comment]
@tcorveleyn taking this item offline with the levelup team.

@swathibhat1 please help the requestor to get help form the levelup team on the identity deployment issues.
