### ISSUE TITLE
[Baseline UI Definition] - Fix null location condition for existing VNET element

### ISSUE THREAD

**Issue by jamasten** [Azure/avdaccelerator#657]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying the baseline, if deploy session hosts is set to false then the existing VNET element / drop down has a null value for the location and can't find any VNETs

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

I was hoping to see my VNETs based on the resource scope if the session host location is null.

**Comment by danycontre** [comment]
@jamasten thank you for your feedback, we are reviewing it.

**Comment by danycontre** [comment]
@jamasten fix was just pushed, please test it and let us know the outcome.

**Comment by jamasten** [comment]
All is well! Thanks for the fix, @danycontre!
