### ISSUE TITLE
Brownfield deployment new session hosts not associated with DCR

### ISSUE THREAD

**Issue by d875167** [Azure/avdaccelerator#662]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying new session hosts via bicep brownfield module with deployMonitoring enabled the deployed session hosts are not associated with the data collection rule so collection of windows event logs is not working.

In the baseline deployment this is done with the module dataCollectionRuleAssociation, is it possible to also add this to the brownfield deployment?

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@d875167 feature added with PR 664.

@swathibhat1
