### ISSUE TITLE
FileShareQuotaIncrease - Need ability to select deployment to existing RG

### ISSUE THREAD

**Issue by JCoreMS** [Azure/avdaccelerator#669]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

During deployment you can name the resources and use the same RG name but the deployment fails.  Need option for user to provide existing Resource Group in scenarios where they've deployed once already and want to deploy to existing RG. 

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

This will provide a method in which all the automation for storage accounts is consolidated in a single RG.

### Please provide the correlation id associated with your error or bug.

N/A

### Can you describe any alternatives that you have taken since this feature does not exist?

Created in another Resource Group and move the resources after the fact but requires some RBAC adjustments as well.

### Feature Implementation

```Shell
No
```

**Comment by danycontre** [comment]
@JCoreMS thanks for your feedback, we are reviewing it.

**Comment by danycontre** [comment]
@swathibhat1 please create an ADO item to work on this new feature.

**Comment by swathibhat1** [comment]
[like]  Swathi Bhat reacted to your message:
________________________________
