### ISSUE TITLE
Start Building Templates to Support UI

### ISSUE THREAD

**Issue by edm-ms** [Azure/avdaccelerator#67]
We need to start taking the existing UI template and adding all the output parameters. This is going to be a bit of heavy lifting as there are many options and a lot of conditional output we will need to pass to downstream templates that do the build.

**Comment by danycontre** [comment]
We are working on finishing the deployment code to then build the portal UI on top

**Comment by danycontre** [comment]
This is a work in progress, we are developing bicep deployment and portal UI at the same time, so they work together.

**Comment by danycontre** [comment]
templates built form bicep code
