### ISSUE TITLE
FileShareQuotaAutoIncrease - Will not deploy on US Gov Cloud

### ISSUE THREAD

**Issue by JCoreMS** [Azure/avdaccelerator#670]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Appears to be an API mismatch error and will not pass validation prior to deployment.

{"code":"InvalidDeployment","message":"Support for symbolic name resources requires a minimum API version of '2020-09-01', but API version '2020-06-01' was supplied."}

### Please provide the correlation id associated with your error or bug.

n/a

### What was the expected outcome?

Deployment

### Relevant log output

```Shell
{"code":"InvalidDeployment","message":"Support for symbolic name resources requires a minimum API version of '2020-09-01', but API version '2020-06-01' was supplied."}
```

**Comment by danycontre** [comment]
@JCoreMS thanks for your feedback, we are reviewing it.

**Comment by danycontre** [comment]
@JCoreMS we just pushed a fix for the portal UI deployment initiator, please try again.
