### ISSUE TITLE
Error when applying CustomScriptExensions

### ISSUE THREAD

**Issue by BenMartinBaur** [Azure/avdaccelerator#673]
### What happened? Provide a clear and concise description of the bug, including deployment details.

After the successful deployment of an hostpool with the AVDAccelerator you can not deploy another CustomerScriptExtension to the session hosts. 

The deployment will fail with the error below. 
The deployment will work if you uninstall the CustomScriptExtension which was deployed through the accelerator. 

### Please provide the correlation id associated with your error or bug.

{"code":"DeploymentFailed","target":"/subscriptions/SUBCRIPTION-ID/resourceGroups/RESOURCEGROUPNAME/providers/Microsoft.Resources/deployments/Microsoft.CustomScriptExtension-20240916121334","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see
https://aka.ms/arm-deployment-operations
for usage details.","details":[{"code":"OperationNotAllowed","message":"Cannot update handlerVersion or autoUpgradeMinorVersion for VM extension 'CustomScriptExtension'. Change is in conflict with other extensions under handler 'Microsoft.Compute.CustomScriptExtension', with typeHandler version '1.10' and autoUpgradeMinorVersion 'True'."}]}

**Comment by danycontre** [comment]
@BenMartinBaur  thanks for your feedback, we are reviewing it.

**Comment by danycontre** [comment]
@BenMartinBaur the version we are using in AVD LZA is 1.10.17, you can only have one version of the Custom Script Extension applied at a time.

The following is a snippet of the extension properties:
  ```
ResourceGroupName       : <RGName>
  VMName                  : <VMName>
  Name                    : AzureFilesDomainJoin
  Location                : <location>
  Etag                    : null
  Publisher               : Microsoft.Compute
  ExtensionType           : CustomScriptExtension
  TypeHandlerVersion      : 1.10
  Id                      : <ID>
  PublicSettings          : 
  ProtectedSettings       : 
  ProvisioningState       : Succeeded
  Statuses                : 
  SubStatuses             : 
  AutoUpgradeMinorVersion : True
  ForceUpdateTag          : 
  EnableAutomaticUpgrade  : False
  InstanceView            :
``` 

However, you can run multiple custom scripts by updating the existing extension with a new configuration or by removing and reapplying the extension with the updated script.

Options for Running Multiple Scripts
1. Update Existing Extension: Modify the configuration of the current Custom Script Extension to include the new script.
2. Reapply Extension: Remove the existing Custom Script Extension and then reapply it with the new script configuration.

The following is an example of updating the script in the extension: 

`Set-AzVMExtension -ResourceGroupName <ResourceGroupName> -VMName <VMName> -Name CustomScriptExtension -Publisher Microsoft.Compute -ExtensionType CustomScriptExtension -TypeHandlerVersion 1.10 -Settings '{"fileUris": ["<URL_to_script>"], "commandToExecute": "./<script_name>.sh"}`'
