### ISSUE TITLE
Bug: Issue with App Attach VM Brownfield Deployment

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#675]
### What happened? Provide a clear and concise description of the bug, including deployment details.

https://github.com/Azure/avdaccelerator/blob/main/workload/bicep/brownfield/appAttachToolsVM/Readme.md

Noticed the following software is not successfully installing during deployment.  I believe the issue may be because the script to call it is using `Add-AppxPackage` instead of `Add-AppxProvisionedPackage`.

- MSIX Packaging Tool
- PSFTooling

`Add-AppPackage -Path "C:\MSIX\MSIXPackagingTool.msixbundle"`
`Add-AppPackage -Path "C:\MSIX\PsfTooling-x64.msix"`

Should be:

`Add-AppxProvisionedPackage -Online -PackagePath "C:\MSIX\MSIXPackagingTool.msixbundle" -SkipLicense | Out-Null`
`Add-AppxProvisionedPackage -Online -PackagePath "C:\MSIX\PsfTooling-x64.msix" -SkipLicense | Out-Null`

I think the URLs may also need to be updated:

**MSIX Packaging Tool:** https://download.microsoft.com/download/e/2/e/e2e923b2-7a3a-4730-969d-ab37001fbb5e/MSIXPackagingtoolv1.2024.405.0.msixbundle

That URL is likely to change with newer versions, so it would be ideal to have a https://aka.ms shortlink or if the PG can provide a reusable URL.

Ref: https://learn.microsoft.com/en-us/windows/msix/packaging-tool/disconnected-environment

**PSFTooling**: https://www.tmurgent.com/APPV/Tools/PsfTooling/PsfTooling-6.10.0.0-x64.msix

**NOTE:** The latest MSIX Packaging Tool has PSF tools within it now. 

### What was the expected outcome?

Expected to see software installed.

**Comment by danycontre** [comment]
@brmcmill thank you for your feedback, we are reviewing.

**Comment by danycontre** [comment]
@JCoreMS please review this issue.

**Comment by JCoreMS** [comment]
Sorry for the length of time for the reply but @brmcmill I'll be working on the updates this week.  It's been a while since updated so in need of it. The URL unfortunately doesn't have an aka.ms but worth asking the PG for.
