### ISSUE TITLE
FSLogix storage account not being domain joined

### ISSUE THREAD

**Issue by michael-novak-80** [Azure/avdaccelerator#683]
Hello @danycontre & team,

I am experiencing a problem during fslogix storage account deployment. **It is not being domain joined.** The Storage account fslogix file share has AD integration as not configured and the object is not created in the AD. The DomainJoin step in the "Add-fslogix-Storage-Setup" completes sucesfully:

![Image](https://github.com/user-attachments/assets/89819db1-dfde-4986-a4eb-51ab2e46b5e2)

- I have deployed ALZ through Bicep accelerator.
- I am using hub and spoke network, with custom DNS servers configured on Hub and AVD spoke vnet. 
- For AVD deployment I am using a dedicated subscription with existing dedicated spoke vnet along with existing private DNS zones and Custom servers (Scenario 4 I suppose). 
- I have thouroughly followed the documentation guidelines regarding DNS resolution configuration for private zones and have linked the vnet containing azure DC VM to both private zones (residing in hub subscription) in addition to a hub network link. 
- I have an on-prem domain controller and a secondary azure domain controller VM setup as a forwarder to Azure DNS. 

Private endpoint resolution works fine from both domain controllers:

```
Non-authoritative answer:
Name:    safslatcpkpb.privatelink.file.core.windows.net
Address:  10.50.1.6
Aliases:  safslatcpkpb.file.core.windows.net
```

There is no corresponding log file in management VM C:\Windows\Temp folder I could reference to. 

Also, the DSCStorageScripts directory is empty, so the script that is supposed to domain join the storage account is not being run at all?

![Image](https://github.com/user-attachments/assets/99380868-1065-4b94-88a7-54bdbab139ca)

I have absolutely no idea what I might be doing wrong. 

### What was the expected outcome?

Storage account joining the domain

**Comment by danycontre** [comment]
@michael-novak-80 thanks for your feedback.

Comments:
- Add-fslogix-Storage-Setup status only checks if the custom script extension on the VM was enabled, it doesn't take in consideration the outcome of the custom script package execution.

Looks like the VM wasn't able to download the DSC package, please check the following in the management  VM:
-- Check if the VM has access to download https://github.com/Azure/avdaccelerator/raw/main/workload/scripts/DSCStorageScripts/1.0.1/DSCStorageScripts.zip this is the package that the extension will unzip inside C:\Windows\Packages\DSCStorageScripts-fslogix\
-- Look for errors on the extension execution C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension

**Comment by danycontre** [comment]
@michael-novak-80 this was a bug in the DSC package file naming, we just pushed a fix for it.

Please try again.

**Comment by michael-novak-80** [comment]
Hi @danycontre 
Thanks for the answer and a quick fix. DSC package is now downloaded and executed correctly. 

HOWEVER,
The script `Script-DoimainJoinStorage.ps1` has still defined the depreciated argument `-EncryptionType 'AES256'` for the `Join-AzStorageAccount`:

`Join-AzStorageAccount -ResourceGroupName $StorageAccountRG -StorageAccountName $StorageAccountName -OrganizationalUnitDistinguishedName $OUName -DomainAccountType 'ComputerAccount' -EncryptionType 'AES256' -OverwriteExistingADObject #-SamAccountName $SamAccountName`

This argument was removed in v 0.2.9 of AzFilesHybrid on Jan 16, 2024:

_Removal of an unused parameter in the Join cmdlet, no longer needed because we are using AES256 as the default encryption type._
https://github.com/Azure-Samples/azure-files-samples/releases

_AES-256 Kerberos encryption is now the only encryption method supported by the AzFilesHybrid module._
https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-ad-ds-enable

Therefore, the script fails with:

```
10-11-24 17:29:15 - MSFT_ScriptResource:25 - [ERROR] 

Exception             : System.Management.Automation.ParameterBindingException: A parameter cannot be found that 
                        matches parameter name 'EncryptionType'.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
                        dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : 
CategoryInfo          : InvalidArgument: (:) [Script-DomainJoinStorage.ps1], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Script-DomainJoinStorage.ps1
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Packages\DSCStorageScripts-fslogix\Script-DomainJoinStorage.ps1: line 121
                        at <ScriptBlock>, <No file>: line 19
                        at ScriptExecutionHelper, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfi
                        guration\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 317
                        at Set-TargetResource, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfigur
                        ation\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 153
PipelineIterationInfo : {}
PSMessageDetails      : 
```

Could you also please edit the 

`https://github.com/Azure/avdaccelerator/blob/main/workload/scripts/DSCStorageScripts/1.0.1/Script-DomainJoinStorage.ps1`

and remove this parameter?

Thank you!

**Comment by danycontre** [comment]
@michael-novak-80 package updated, please try again and let us know the outcome.

**Comment by michael-novak-80** [comment]
Hi @danycontre 

Confirming it works fine now. Many thanks for your support. 

> [@michael-novak-80](https://github.com/michael-novak-80) package updated, please try again and let us know the outcome.
