### ISSUE TITLE
error on GOV deployment: Cannot create diag settings on VNET

### ISSUE THREAD

**Issue by gusdellazure** [Azure/avdaccelerator#685]
### What happened? Provide a clear and concise description of the bug, including deployment details.

error on GOV deployment: Cannot create diag sertings on VNET

{"code":"BadRequest","message":"CategoryGroup: 'allLogs' is not supported, supported ones are: ''"}

CategoryGroup: 'allLogs' is not supported, supported ones are: '' (Code: BadRequest, Target: /subscriptions/cf4d6247-bf51-42e6-9dd5-caa709737200/resourceGroups/rg-avd-avd-prod-va-network/providers/Microsoft.Network/virtualNetworks/vnet-avd-prod-va-001/providers/Microsoft.Insights/diagnosticSettings/vnet-avd-prod-va-001-diagnosticSettings)

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@gusdellazure thanks for your feedback, we just merged the PR #687 to fix the bug, please try again.

@swathibhat1
