### ISSUE TITLE
managedDisk.securityProfile.securityEncryptionType' is missing (null)

### ISSUE THREAD

**Issue by gusdellazure** [Azure/avdaccelerator#686]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Issue with deploying .GOV 

  "code": "DeploymentFailed",
  "target": "/subscriptions/cf4d6247-bf51-42e6-9dd5-XXXXXXX/resourceGroups/rg-avd-avd-prod-va-service-objects/providers/Microsoft.Resources/deployments/MGMT-VM-20241015T003002Z",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "Required parameter for Confidential VMs 'managedDisk.securityProfile.securityEncryptionType' is missing (null)."
    }
  ]
}

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@gusdellazure thank you for your feedback, we are reviewing it.

**Comment by chbragg** [comment]
@gusdellazure , is your issue resolved when you deploy with the supported settings around Confidential Compute or Trusted Launch as described above?

**Comment by gusdellazure** [comment]
Hi all yes the fox worked!! thank you
