### ISSUE TITLE
Change Request - Storage Account Diagnostic settings

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [Azure/avdaccelerator#688]
### Let us know the feedback or general question

At present the Storage accounts are configured with the settings "default-diagnosticSettings" configured to capture allLogs. This means a log of every read, write, and delete. At scale, this cost becomes massive. I would suggest this be changed to only collecting storage metrics. Currently 87% of my Log Analytics cost is StorageFileLogs, and this cost is quickly growing out of control. I am paying as much for logging as I am my compute costs. See attached for more details.

[Image](https://github.com/user-attachments/assets/8c4f3b74-f4d9-4398-88a0-ebaf623b5487)
![Image](https://github.com/user-attachments/assets/f263907d-7a09-40d2-8bdd-bc4e1a3dfd20)

**Comment by danycontre** [comment]
@OrionWithrow-OHIT this is great feedback, we are acting on it.

**Comment by danycontre** [comment]
@OrionWithrow-OHIT an update (PR  #689 ) was pushed to remove logs from storage accounts and virtual networks, this resource will now only send metrics to the log analytics workspace.

@swathibhat1
