### ISSUE TITLE
Organization Azure Policy Initiative is causing this to fail

### ISSUE THREAD

**Issue by jwaltireland** [Azure/avdaccelerator#694]
we have a policy initiative that restricts the region in which avd resources can be deployed.  i'm using github actions, and using the azure/arm-deploy@v2 action, with  deploymentMode: 'Validate'.  (NOTE That we first discovered the issue trying to deploy without the deploymentMode)

the allowed list of regions in the policy iniative:
["westus3", "westus2", "westus2stage", "westusstage", "westus", "westcentralus", "unitedstates", "southcentralusstage", "southcentralus", "northcentralus", "northcentralusstage", "global", "eastus2stage", "eastus2", "eastusstage", "eastus", "centralusstage", "centralus"]

In the bicep code, we're only using eastus2.  I've been commenting out the code and testing each module from the base bicep.  Once i got to the identity module, the error occurred.

At this location, module scalingPlanRoleAssignCompute:  
https://github.com/Azure/avdaccelerator/blob/aa5139e8d9c14afbad4c17308c9b56e396291c38/workload/bicep/modules/identity/deploy.bicep#L118

i've even validated that the module storageContributorRoleAssign, which comes after the scalingPlanRoleAssignCompute (commented out the scalingPlanRoleAssignCompute), validates fine.

What is the issue with the scalingPlanRoleAssignCompute?

**Comment by jwaltireland** [comment]
policy violation error, i had to redact organizational data:  

***"code": "RequestDisallowedByPolicy", "target": "{redacted}", "message": "Resource '{redacted}' was disallowed by policy. Reasons: 'This action is out of compliance with the {redacted} managed polices. Please contact @mail.*** for more information.'. See error details for policy resource IDs.", "additionalInfo": [***"type": "PolicyViolation", "info": ***"evaluationDetails": ***"evaluatedExpressions": [***"result": "False", "expressionKind": "Field", "expression": "location", "path": "location", "targetValue": ["westus3", "westus2", "westus2stage", "westusstage", "westus", "westcentralus", "unitedstates", "southcentralusstage", "southcentralus", "northcentralus", "northcentralusstage", "global", "eastus2stage", "eastus2", "eastusstage", "eastus", "centralusstage", "centralus"], "operator": "In"***], "reason": "This action is out of compliance with the {organization) managed polices. Please contact @mail.*** for more information."***, "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/{redacted}/providers/Microsoft.Authorization/policyDefinitions/{redacted}", "policySetDefinitionId": "/providers/Microsoft.Management/managementGroups/{redacted}/providers/Microsoft.Authorization/policySetDefinitions/{redacted}", "policyDefinitionReferenceId": "{redacted}", "policySetDefinitionName": "{redacted}", "policySetDefinitionDisplayName": "{redacted}-Initiative", "policyDefinitionName": "{redacted}", "policyDefinitionDisplayName": "Audit-Resource-Location", "policyDefinitionEffect": "deny", "policyAssignmentId": "/providers/Microsoft.Management/managementGroups/{redacted}/providers/Microsoft.Authorization/policyAssignments/{redacted}", "policyAssignmentName": "{redacted}", "policyAssignmentDisplayName": "{redacted}-Policy-Initiative", "policyAssignmentScope": "/providers/Microsoft.Management/managementGroups/{redacted}", "policyAssignmentParameters": ***, "policyExemptionIds": []***]***

**Comment by jwaltireland** [comment]
I tested in a personal subscription.  I created the policy:

        "in": "[parameters('allowedLocations')]"
      }
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {
    "allowedLocations": {
      "type": "Array",
      "metadata": {
        "displayName": "Allowed locations",
        "description": "The list of allowed locations for resources.",
        "strongType": "location"
      }
    }
  }
}

and when i assigned it, i used these US regions:  ["westus3", "westus2", "westus2stage", "westusstage", "westus", "westcentralus", "unitedstates", "southcentralusstage", "southcentralus", "northcentralus", "northcentralusstage", "global", "eastus2stage", "eastus2", "eastusstage", "eastus", "centralusstage", "centralus"]

and i got the same error.

Something is wrong w/the bicep

**Comment by danycontre** [comment]
@jwaltireland thanks for the info.

Comments:

- What is the reason to use a custom policy instead of the built-in one?
  - Built-in policy name: Allowed locations
  - Built-in policy definition ID: /providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c 

We haven't been able to reproduce the issue using the built-in policy, the following is a snap of parts of the built-in policy definition:

"mode": "Indexed"
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "location",
            "notIn": "[parameters('listOfAllowedLocations')]"
          },
          {
            "field": "location",
            "notEquals": "global"
          },
          {
            "field": "type",
            "notEquals": "Microsoft.AzureActiveDirectory/b2cDirectories"
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }

**Comment by jwaltireland** [comment]
> [@jwaltireland](https://github.com/jwaltireland) thanks for the info.
> 
> Comments:
> 
> * What is the reason to use a custom policy instead of the built-in one?
>   
>   * Built-in policy name: Allowed locations
>   * Built-in policy definition ID: /providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c
> 
> We haven't been able to reproduce the issue using the built-in policy, the following is a snap of parts of the built-in policy definition:
> 
> "mode": "Indexed" "policyRule": { "if": { "allOf": [ { "field": "location", "notIn": "[parameters('listOfAllowedLocations')]" }, { "field": "location", "notEquals": "global" }, { "field": "type", "notEquals": "Microsoft.AzureActiveDirectory/b2cDirectories" } ] }, "then": { "effect": "deny" } }


I didn't know a builtin one existed.  let me try it

**Comment by jwaltireland** [comment]
@danycontre Ok, thanks!  i think we found the issue:  our policy is using mode = All;  builtin in using Indexed:   

all: evaluate resource groups, subscriptions, and all resource types
indexed: only evaluate resource types that support tags and location
