### ISSUE TITLE
Bug: Custom Image Build Deploy to Azure/Azure Gov URIs may need to be updated on Getting Started... Doc

### ISSUE THREAD

**Issue by brmcmill** [Azure/avdaccelerator#695]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Hey Team!  Noticing the Deploy to Azure/Azure Gov URI interactive buttons are not taking you to a template to deploy when clicked.  Hope this helps!

The page that you navigate through the main repo seems to be working fine (https://github.com/Azure/avdaccelerator?tab=readme-ov-file#custom-image-build)
 It this "Getting Started..." doc that needs to be fixed.

https://github.com/Azure/avdaccelerator/blob/main/workload/docs/getting-started-custom-image-build.md

![Image](https://github.com/user-attachments/assets/c1f15bd9-ca40-4aae-b300-4d2b3c364f79)

### Please provide the correlation id associated with your error or bug.

N/A

### What was the expected outcome?

Deploying to an Azure Tenant UI is available.

**Comment by danycontre** [comment]
@brmcmill thanks for your feedback, bug has been fixed with PR #696
