### ISSUE TITLE
VDOT doesn't run during Set-SessionHostConfiguration script

### ISSUE THREAD

**Issue by chbragg** [Azure/avdaccelerator#698]
### What happened? Provide a clear and concise description of the bug, including deployment details.

VDOT appears to not run during the Set-SessionHostConfiguration script. It appears that there was potentially an if statement in the script that has been removed and there are brackets leftover "{}" which prevents VDOT from running. To validate if VDOT runs properly, check the event log for "Virtual Desktop Optimization Tool" after AVD is provisioned.

![Image](https://github.com/user-attachments/assets/d7b8f0fb-cb7c-413b-86a6-c8ae8b5b034f)

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by danycontre** [comment]
@chbragg thanks for your feedback we are reviewing.

**Comment by danycontre** [comment]
@chbragg  thank you for your contribution, we have decided to remove VDOT functionality from the code given the variability of what customers could want to be part of the image.

@swathibhat1
