### ISSUE TITLE
Greenfield - New deployment fails Workload-KeyVault

### ISSUE THREAD

**Issue by kramer06** [Azure/avdaccelerator#707]
### What happened? Provide a clear and concise description of the bug, including deployment details.

New Greenfield deployment fails at the Workload-KeyVault. The deployment has completed successfully multiple times, however in the past few days the deployment stops at this spot each time. 

### Please provide the correlation id associated with your error or bug.

98e0d399-e6db-480f-b101-db0aaf561555

### Relevant log output

{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/subscriptions/###/resourceGroups/rg-avd-cln-prd-cc-service-objects/providers/Microsoft.Resources/deployments/Workload-KeyVault-20241105T142629Z' at line '19897' and column '5'. 'The language expression property array index '8' is out of bounds.'","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":19897,"linePosition":5,"path":""}}]}

{
  "code": "InvalidTemplate",
  "message": "Unable to process template language expressions for resource '/subscriptions/####/resourceGroups/rg-avd-cln-prd-cc-service-objects/providers/Microsoft.Resources/deployments/Workload-KeyVault-20241105T142629Z' at line '19897' and column '5'. 'The language expression property array index '8' is out of bounds.'",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 19897,
        "linePosition": 5,
        "path": ""
      }
    }
  ]
}

**Comment by danycontre** [comment]
@kramer06 thanks for reporting the issue.

Bug has been fixed with PR #708
