### ISSUE TITLE
Make available for deployment on CSP sub.

### ISSUE THREAD

**Issue by MTersago** [Azure/avdaccelerator#712]
### Let us know the feedback or general question

Would it be possible to allow the deployment of the accelerator on Azure CSP subs please?

**Comment by MTersago** [comment]
![Image](https://github.com/user-attachments/assets/569a66f4-7996-4807-820b-ecbd9a03546c)

**Comment by danycontre** [comment]
@MTersago thanks for your feedback we are reviewing.

@swathibhat1

**Comment by danycontre** [comment]
@swathibhat1 the AVD LZA will need to be included as an offer on the partner center, please contact the partner/business team.

@MTersago we are working internally to make it available.

**Comment by MTersago** [comment]
The AVD LZA is not available on MSFT Partner Center, see screenshot below.

***@***.***

**Comment by MTersago** [comment]
Screenshot does show in my email reply above, adding it here:
![Image](https://github.com/user-attachments/assets/ac83313c-6df7-4fca-abab-112a18727e5f)
