### ISSUE TITLE
avdMonitoring.bicep

### ISSUE THREAD

**Issue by CraigGardinerDXC** [Azure/avdaccelerator#715]
### What happened? Provide a clear and concise description of the bug, including deployment details.

When deploying the AVD Diagnostic policies using the file  "avdMonitoring.bicep" I'm receiving the following error: 
{
  "code": "DeploymentFailed",
  "target": "/subscriptions//providers/Microsoft.Resources/deployments/Policy-Set-Definition-20241118T122809Z",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "InvalidRequestContent",
      "message": "The request content was invalid and could not be deserialized: 'Error converting value \"/subscriptions//resourceGroups//providers/Microsoft.OperationalInsights/workspaces/\" to type 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.PolicyParameterDefinition'. Path 'properties.parameters.logAnalytics', line 1, position 581.'."
    }
  ]
}

### Please provide the correlation id associated with your error or bug.

38988541-bce9-4fd2-8155-882bfd872687

### What was the expected outcome?

The  policy initiative would be created with the required parameters.

### Relevant log output

```Shell
{"code":"DeploymentFailed","target":"/subscriptions//providers/Microsoft.Resources/deployments/Policy-Set-Definition-20241118T122809Z","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Error converting value \"/subscriptions//resourceGroups/rg-avd-hisp-prd-uks-monitoring/providers/Microsoft.OperationalInsights/workspaces/logavdprduks\" to type 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.PolicyParameterDefinition'. Path 'properties.parameters.logAnalytics', line 1, position 581.'."}]}
```

**Comment by danycontre** [comment]
@CraigGardinerDXC thanks for your feedback we are reviewing.

**Comment by danycontre** [comment]
@CraigGardinerDXC please let us know if you are still having this issue? if so:

- Are you using existing or new log analytics workspace?
- Are you deploying to Azure public?
