### ISSUE TITLE
Fail to Add New Host Session with Standard security type

### ISSUE THREAD

**Issue by WelsonPS** [Azure/avdaccelerator#718]
When I try to add new hosts with the ‘Add-New-Hosts-session’ script, it always returns a deployment failure. In the environment, the host needs to be of the Standard security type because the gallery image was created as standard.

![Image](https://github.com/user-attachments/assets/a6c335b6-beae-49aa-bd7a-40c07c060242)

Is there any tip, workaround or fix for this failure?

Detail: The hostpool and AVD works fine, but the problem is with to add new hosts.

**Comment by danycontre** [comment]
@WelsonPS thanks for reporting the issue.

Please go to the resource group deployments, select SH-0* and share template content and inputs, this will help us troubleshoot the issue.

**Comment by WelsonPS** [comment]
Hi @danycontre, thanks for your attention! :)

It's the RG deployment content:

![Image](https://github.com/user-attachments/assets/8303a46e-ee7e-40fe-a523-345ba5ceff3d)

The raw error:
[deployment.json](https://github.com/user-attachments/files/18013900/deployment.json)

[deployment.json](https://github.com/user-attachments/files/18013902/deployment.json)

Arm template:
https://github.com/Azure/avdaccelerator/blob/main/workload/bicep/brownfield/newSessionHosts/readme.md

Do you need more information?

**Comment by danycontre** [comment]
@WelsonPS there was a change in the API, we have pushed the fix to branch https://github.com/Azure/avdaccelerator/tree/issue-718

Please run a deployment form the fix branch and let us know the outcome.

**Comment by danycontre** [comment]
PW merged.
