### ISSUE TITLE
Feature Request - Dynamic autoscaling

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [Azure/avdaccelerator#719]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Do you have an ETA for deploying Host Pools and Dynamic autoscaling for pooled host pools and Scaling Plans?

https://learn.microsoft.com/en-us/azure/virtual-desktop/autoscale-create-assign-scaling-plan?tabs=portal%2Cintune&pivots=dynamic

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

The community is eager to implement this feature and begin testing.

### Can you describe any alternatives that you have taken since this feature does not exist?

Only alternative is to deploy a new Host Pool manually

### Feature Implementation

```Shell

```

**Comment by danycontre** [comment]
@OrionWithrow-OHIT thanks for your feedback.

@swathibhat1

**Comment by danycontre** [comment]
@OrionWithrow-OHIT closing issue, but we have added the feature request to our backlog.
