### ISSUE TITLE
BUG: NSG and RT assignments missing on subnets

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/avdaccelerator#723]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Virtual network deployment fails if deploying in an ALZ environment where each subnet is required to have a network security group assigned. Even a default network security group would meet those requirements.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

Customer adoption of CAF ALZ is increasing and the AVD accelerator should seamlessly deploy in it.

### Please provide the correlation id associated with your error or bug.

fb5969cd-e1c8-43dc-abeb-85abda6a8b6e

### Can you describe any alternatives that you have taken since this feature does not exist?

Start deployment, wait for the deployment to fail, and exclude the AVD network RG from the policy assignment using the CAF Bicep or TF, redeploy the ALZ to deploy the exclusion, then re-deploy the AVD accelerator.

### Feature Implementation

```Shell
Pending
```

**Comment by SvenAelterman** [comment]
Looking through the code, it seems like NSGs are supposed to be assigned (at least, they are created and a cursory review of the code indicates their resource IDs are used later). However, the subnets in my virtual network do not have NSGs created.

**Comment by SvenAelterman** [comment]
I've identified the cause of this and it's a bug. The AVD accelerator network module creates a custom object containing the properties `networkSecurityGroupId` and `routeTableId` but the AVM module performing the deployment expects `networkResourceGroupResourceId` and `routeTableResourceId`.

I will submit a PR.

**Comment by danycontre** [comment]
@SvenAelterman great catch, thank you for your contribution.
