### ISSUE TITLE
Baseline deployment error (addAzureFilesToADDSScript)

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#75]
New-AzSubscriptionDeployment : 8:50:24 AM - The deployment 'CARML-workload-20220421T0804312802Z' failed with error(s). Showing 1 out of 1 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: 
DeploymentFailed)
 - {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'addAzureFilesToADDSScript'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code 
of: '1'. The command had an error output of: 'C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.12\\Downloads\\0\\Manual-DSC-JoinStorage-to-ADDS.ps1 : \r\nMissing an argument for 
parameter 'OUName'. Specify a parameter of type 'System.String' and try again.\r\n    + CategoryInfo          : Inv...' For more information, check the instance view by executing Get-AzVmssVm or 
Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at 
https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
      }
    ]
  }
} (Code:Conflict)
CorrelationId: 63bc9cae-f289-4896-ae35-691e01d00709
At line:57 char:1
+ New-AzSubscriptionDeployment @inputObject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDeploymentCmdlet

**Comment by pauldotyu** [comment]
Re-tested this and no longer seems to be an issue. The "Provisioning state" for the "tempstgvm/addAzureFilesToADDSScript" extension is reporting "Succeeded" and I have verified a new OU for storage was created in ADDS.
