### ISSUE TITLE
Baseline deployment error (principal not available)

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#76]
New-AzSubscriptionDeployment : 8:44:31 AM - The deployment 'CARML-workload-20220421T0804576774Z' failed with error(s). Showing 3 out of 6 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for 
usage details. (Code: DeploymentFailed)
 - {
  "error": {
    "code": "PrincipalNotFound",
    "message": "Principal 0f14a80d42e54d57afe046acf9dfae05 does not exist in the directory c7cb8e56-3c8d-431c-a94c-866e27a25b45. Check that you have the correct 
principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the 
role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
  }
} (Code:BadRequest)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for 
usage details. (Code: DeploymentFailed)
 - {
  "error": {
    "code": "PrincipalNotFound",
    "message": "Principal 0f14a80d42e54d57afe046acf9dfae05 does not exist in the directory c7cb8e56-3c8d-431c-a94c-866e27a25b45. Check that you have the correct 
principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the 
role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
  }
} (Code:BadRequest)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for 
usage details. (Code: DeploymentFailed)

**Comment by pauldotyu** [comment]
Resolved in #99
