### ISSUE TITLE
Baseline deployment error (InvalidAddressPrefixFormat) 

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#83]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "InvalidAddressPrefixFormat",
      "message": "Address prefix [[if(equals(steps('avdNetwork').createAvdVnet, true), steps('avdNetwork').avdVnetSize, '10.10.0.0/23')] of resource /subscriptions/a7bc841f-34c0-4214-9469-cd463b66de35/resourceGroups/rg-westcentralus-avd-ap71-network/providers/Microsoft.Network/virtualNetworks/vnet-westcentralus-avd-ap71 is not formatted correctly. It should follow CIDR notation, for example 10.0.0.0/24."
    }
  ]
}

**Comment by danycontre** [comment]
Typo in the portal UI output definition

**Comment by yuanyuanchen-tech** [comment]
Hello, could you please tell me the solution of this problem? Cause I also meet it now.
