### ISSUE TITLE
Guidance for regional expansion

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#85]
Simona contribution: https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosofteur-my.sharepoint.com%2F%3Aw%3A%2Fg%2Fpersonal%2Fsitarant_microsoft_com%2FEeoIjX6lysRBvpWzrlnrx4MBzRUWmSi1zba_-tJUD67bwA%3Fe%3DIXyLcf&data=05%7C01%7Cdany.contreras%40microsoft.com%7Cfe900fbba94642a2399d08da1bf7fdca%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637853049188129591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PaC0SE9hmP2f3Tc1IOKC%2BUtLhMzHyqKzboV%2FeqvFFiI%3D&reserved=0

**Comment by swathibhat1** [comment]
Feature/Enhancement moved into ADO for tracking
