### ISSUE TITLE
CARML team feedback - improve dependencies

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#92]
[11:06 AM] Alexander Sehr
I also see a lot of dependencies that can be removed. With the later Bicep versions Linter should automatically complain about them too

[11:23 AM] Alexander Sehr
Also a question - why is there a key vault & storage account deployment at the and of the image template. Neither seems to be used post-deployment

[11:25 AM] Alexander Sehr
Also, you could reduce the AVD template further by deploying e.g. the RGs & NSGs using a loop, instead of specifying them one by one

[11:26 AM] Alexander Sehr
An example with a different resource:

<img width="614" alt="Screenshot 2022-04-28 163344" src="https://user-images.githubusercontent.com/78437433/165849463-54e7da6d-9947-4d61-aca6-4a0e4818dfa7.png">

 But I hope it gets the idea across. You could have an array of the RG-Names and just loop over it. It's always the same anyways

**Comment by nataliakon** [comment]
main baseline reformatted to modular approach and CARML team suggestions.
