### ISSUE TITLE
Docs: Update landing page with new diagram and update link to repo

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#98]
just realized we need to update diagram and links on the landing page ([Enterprise-scale support for Azure Virtual Desktop - Cloud Adoption Framework | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/enterprise-scale-landing-zone)), especially the link under Custom deployment is pointing to RDS-Templates repository

**Comment by xelizondo** [comment]
[PR #3406 posted](https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3406)

**Comment by danycontre** [comment]
Thanks for the great work Xavier, closing this one

**Comment by xelizondo** [comment]
@danycontre , The PR is assigned to Wahid as reviewer but he is on long term vacation. Who else can we assign it to?
